package cn.lvxu.travel;
import java.util.*;import java.math.BigDecimal;import org.json.*;
/** Local ledger. Positive balances are receivable; transfers never add spending. */
final class AaLedger {
 static long integer(JSONObject o,String field){try{return Trip.amount(new BigDecimal(o.get(field).toString()).longValueExact());}catch(Exception e){throw new IllegalArgumentException("分账金额须为整数分");}}
 static LinkedHashMap<String,Long> equal(long amount,List<String> people){Trip.amount(amount);if(people.isEmpty()||people.size()>50||new HashSet<>(people).size()!=people.size())throw new IllegalArgumentException("请选择不重复的参与人");LinkedHashMap<String,Long> out=new LinkedHashMap<>();long q=amount/people.size(),r=amount%people.size();for(int i=0;i<people.size();i++)out.put(people.get(i),q+(i<r?1:0));return out;}
 static LinkedHashMap<String,Long> allocation(long amount,List<String> people,Trip.Expense old){if(old!=null&&old.amount==amount&&!old.payerId.isEmpty()&&people.size()==old.shares.size()&&new HashSet<>(people).equals(old.shares.keySet()))return new LinkedHashMap<>(old.shares);return equal(amount,people);}
 static void validate(Trip t){Set<String> members=new HashSet<>();if(t.members.size()>50||t.settlements.size()>5000)throw new IllegalArgumentException("分账记录超过上限");for(Trip.Member m:t.members)if(Trip.empty(m.id)||m.id.length()>100||!members.add(m.id)||Trip.empty(m.name)||m.name.length()>40)throw new IllegalArgumentException("成员资料无效或 ID 重复");Set<String> expenses=new HashSet<>();for(Trip.Expense e:t.expenses){if(!expenses.add(e.id))throw new IllegalArgumentException("账单 ID 重复");if(e.payerId.isEmpty()){if(!e.shares.isEmpty())throw new IllegalArgumentException("分摊账单缺少付款人");continue;}if(!members.contains(e.payerId)||e.shares.isEmpty()||e.shares.size()>50)throw new IllegalArgumentException("分摊账单成员引用无效");long sum=0;for(Map.Entry<String,Long> p:e.shares.entrySet()){if(!members.contains(p.getKey())||p.getValue()==null)throw new IllegalArgumentException("分摊参与人不存在");sum=Math.addExact(sum,Trip.amount(p.getValue()));}if(sum!=e.amount)throw new IllegalArgumentException("分摊合计与账单金额不符");}Set<String> transfers=new HashSet<>();for(Trip.Settlement s:t.settlements){if(Trip.empty(s.id)||!transfers.add(s.id)||!members.contains(s.fromId)||!members.contains(s.toId)||s.fromId.equals(s.toId)||s.amount<=0)throw new IllegalArgumentException("转账记录或成员引用无效");Trip.amount(s.amount);java.time.LocalDateTime.parse(s.occurredAt);}}
 static LinkedHashMap<String,Long> balances(Trip t){validate(t);LinkedHashMap<String,Long> out=new LinkedHashMap<>();for(Trip.Member m:t.members)out.put(m.id,0L);for(Trip.Expense e:t.expenses)if(!e.payerId.isEmpty()){out.put(e.payerId,out.get(e.payerId)+e.amount);for(Map.Entry<String,Long> p:e.shares.entrySet())out.put(p.getKey(),out.get(p.getKey())-p.getValue());}for(Trip.Settlement s:t.settlements){out.put(s.fromId,out.get(s.fromId)+s.amount);out.put(s.toId,out.get(s.toId)-s.amount);}return out;}
 static final class Payment{final String fromId,toId;final long amount;Payment(String f,String t,long n){fromId=f;toId=t;amount=n;}}
 static ArrayList<Payment> payments(Trip t){Map<String,Long> net=balances(t);ArrayList<String> ids=new ArrayList<>(net.keySet());Collections.sort(ids);ArrayList<Payment> out=new ArrayList<>();for(String debtor:ids)if(net.get(debtor)<0)for(String creditor:ids)if(net.get(creditor)>0){long n=Math.min(-net.get(debtor),net.get(creditor));out.add(new Payment(debtor,creditor,n));net.put(debtor,net.get(debtor)+n);net.put(creditor,net.get(creditor)-n);if(net.get(debtor)==0)break;}return out;}
 static void remap(Trip t,Map<String,String> ids){for(Trip.Expense e:t.expenses){if(!e.payerId.isEmpty())e.payerId=required(ids,e.payerId);LinkedHashMap<String,Long> next=new LinkedHashMap<>();for(Map.Entry<String,Long> p:e.shares.entrySet())next.put(required(ids,p.getKey()),p.getValue());e.shares.clear();e.shares.putAll(next);}for(Trip.Settlement s:t.settlements){s.fromId=required(ids,s.fromId);s.toId=required(ids,s.toId);}}
 private static String required(Map<String,String> ids,String key){String value=ids.get(key);if(value==null)throw new IllegalArgumentException("分账成员引用缺失");return value;}
 static void regenerate(Trip t){validate(t);Map<String,String> ids=new HashMap<>();for(Trip.Member m:t.members){String old=m.id;m.id=Trip.uid();ids.put(old,m.id);}remap(t,ids);for(Trip.Settlement s:t.settlements)s.id=Trip.uid();}
 static String label(Trip t,String id){for(int i=0;i<t.members.size();i++){Trip.Member m=t.members.get(i);if(m.id.equals(id))return m.name+" · "+(i+1);}return "成员不存在";}
}
