package cn.lvxu.travel;
import android.app.*;import android.os.Bundle;import android.view.View;import android.widget.*;import java.time.*;import java.util.*;
/** Virtual team members and actual payments stay on this device and in explicit full shares. */
final class AaUi {
 private final MainActivity a;private AlertDialog memberWindow,ledgerWindow;
 AaUi(MainActivity a){this.a=a;}
 void members(Trip t){if(memberWindow!=null)memberWindow.dismiss();LinearLayout f=a.col();f.addView(a.text("一个人可以代记全队，不需要注册或邀请。同名成员按编号区分。旧账单不会自动分摊。",13,a.MUTED));for(Trip.Member m:t.members){f.addView(a.action(AaLedger.label(t,m.id)+(m.archived?"（已停用）":""),false,()->member(t,m)));}f.addView(a.action("＋ 添加成员",true,()->member(t,null)));a.pad(f,22);ScrollView scroll=new ScrollView(a);scroll.addView(f);memberWindow=new RoundedDialogs.Builder(a).setTitle("同行成员").setView(scroll).setPositiveButton("完成",(d,w)->a.render()).show();}
 private void member(Trip t,Trip.Member old){LinearLayout f=a.col();EditText name=a.field(f,"成员称呼",old==null?"":old.name,1);CheckBox archived=new CheckBox(a);archived.setText("停用成员（保留原账单和转账）");archived.setTextColor(a.INK);archived.setChecked(old!=null&&old.archived);if(old!=null)f.addView(archived);a.dialog(old==null?"添加本地成员":"编辑成员",f,()->{if(!a.trips.contains(t))throw new IllegalArgumentException("旅行已变化");if(old==null&&t.members.size()>=50)throw new IllegalArgumentException("最多 50 位成员");String n=a.required(name,40);Trip.Member m=old==null?new Trip.Member():old;String before=m.name;boolean previous=m.archived;m.name=n;m.archived=archived.isChecked();if(old==null)t.members.add(m);if(!a.save()){if(old==null)t.members.remove(m);else{m.name=before;m.archived=previous;}throw new IllegalArgumentException("成员未保存，请重试");}a.render();members(t);},null);}
 void ledger(Trip t){ledger(t,30);}
 private void ledger(Trip t,int limit){if(ledgerWindow!=null)ledgerWindow.dismiss();LinearLayout f=a.col();Map<String,Long> net=AaLedger.balances(t);for(Trip.Member m:t.members){long n=net.get(m.id);f.addView(a.text(AaLedger.label(t,m.id)+" · "+(n>0?"待收 ¥":n<0?"待付 ¥":"已平账 ¥")+FinanceUi.money(Math.abs(n)),15,a.INK));}f.addView(a.text("余额由参与 AA 的原账单和实际转账计算；个人账单不参与。修改原账单会重新计算，历史转账会保留。",12,a.MUTED));ArrayList<AaLedger.Payment> suggestions=AaLedger.payments(t);if(suggestions.isEmpty())f.addView(a.text("暂无未结余额",14,a.GREEN));for(AaLedger.Payment p:suggestions)f.addView(a.action(AaLedger.label(t,p.fromId)+" → "+AaLedger.label(t,p.toId)+" ¥"+FinanceUi.money(p.amount),false,()->transfer(t,p)));if(t.members.size()>1)f.addView(a.action("记录实际转账",true,()->transfer(t,null)));f.addView(a.text("实际转账记录",15,a.INK));for(int i=t.settlements.size()-1;i>=Math.max(0,t.settlements.size()-limit);i--){Trip.Settlement s=t.settlements.get(i);f.addView(a.action(AaLedger.label(t,s.fromId)+" → "+AaLedger.label(t,s.toId)+" ¥"+FinanceUi.money(s.amount)+" · "+s.occurredAt.replace('T',' '),false,()->a.confirm("删除这条实际转账？剩余余额将重新计算。",()->{int at=t.settlements.indexOf(s);if(at<0)return;t.settlements.remove(at);if(!a.save()){t.settlements.add(at,s);return;}a.render();ledger(t);})));}if(t.settlements.size()>limit)f.addView(a.action("加载更多转账（剩余 "+(t.settlements.size()-limit)+" 条）",false,()->{if(ledgerWindow!=null)ledgerWindow.dismiss();ledger(t,limit+30);}));a.pad(f,22);ScrollView scroll=new ScrollView(a);scroll.addView(f);ledgerWindow=new RoundedDialogs.Builder(a).setTitle("AA 结算").setView(scroll).setPositiveButton("关闭",null).show();}
 private void transfer(Trip t,AaLedger.Payment p){LinearLayout f=a.col();ArrayList<String> ids=new ArrayList<>();String[] names=new String[t.members.size()];for(int i=0;i<names.length;i++){ids.add(t.members.get(i).id);names[i]=AaLedger.label(t,ids.get(i));}Spinner from=a.select(f,"转账人",names,p==null?names[0]:AaLedger.label(t,p.fromId)),to=a.select(f,"收款人",names,p==null?names[1]:AaLedger.label(t,p.toId));EditText money=a.field(f,"实际已转金额（人民币）",p==null?"":FinanceUi.money(p.amount),8194),when=DateTimeFields.dateTime(a,f,"转账时间",LocalDateTime.now().withSecond(0).withNano(0).toString());f.addView(a.text("保存即记录已发生的转账，可记录部分金额；不会重复计入旅行支出。",12,a.MUTED));a.dialog("记录实际转账",f,()->{if(!a.trips.contains(t))throw new IllegalArgumentException("旅行已变化");if(t.settlements.size()>=5000)throw new IllegalArgumentException("转账记录已达上限");Trip.Settlement s=new Trip.Settlement();s.fromId=ids.get(from.getSelectedItemPosition());s.toId=ids.get(to.getSelectedItemPosition());s.amount=Trip.cents(money.getText().toString());LocalDateTime date=DateTimeValues.parse(when.getText().toString(),null);if(date==null)throw new IllegalArgumentException("请选择有效转账时间");s.occurredAt=date.withSecond(0).withNano(0).toString();t.settlements.add(s);try{AaLedger.validate(t);if(!a.save())throw new IllegalArgumentException("转账未保存，请重试");}catch(RuntimeException ex){t.settlements.remove(s);throw ex;}a.render();ledger(t);},null);}
 static final class ExpenseFields {
  final MainActivity a;final Trip t;final Trip.Expense original;final CheckBox enabled;final Spinner payer;final ArrayList<String> ids=new ArrayList<>();final LinkedHashMap<String,CheckBox> participants=new LinkedHashMap<>();
  ExpenseFields(MainActivity a,LinearLayout form,Trip t,Trip.Expense old){this.a=a;this.t=t;this.original=old;boolean existing=old!=null&&!old.payerId.isEmpty();if(t.members.size()<2&&!existing){enabled=null;payer=null;return;}enabled=new CheckBox(a);enabled.setText("这笔费用参与 AA");enabled.setTextColor(a.INK);enabled.setChecked(existing);form.addView(enabled);LinearLayout details=a.col();form.addView(details);String[] names=new String[t.members.size()];for(int i=0;i<names.length;i++){ids.add(t.members.get(i).id);names[i]=AaLedger.label(t,ids.get(i));}payer=a.select(details,"付款人",names,existing?AaLedger.label(t,old.payerId):names[0]);details.addView(a.text("参与人（平均分摊；尾差按以下顺序各加 1 分）",12,a.MUTED));for(Trip.Member m:t.members){CheckBox box=new CheckBox(a);box.setText(AaLedger.label(t,m.id)+(m.archived?"（已停用）":""));box.setTextColor(a.INK);box.setChecked(existing?old.shares.containsKey(m.id):!m.archived);box.setEnabled(!m.archived||(existing&&old.shares.containsKey(m.id)));details.addView(box);participants.put(m.id,box);}details.setVisibility(enabled.isChecked()?View.VISIBLE:View.GONE);enabled.setOnCheckedChangeListener((button,value)->details.setVisibility(value?View.VISIBLE:View.GONE));if(!t.settlements.isEmpty())details.addView(a.text("已有实际转账；变更这笔分摊后，余额会重新计算，实际转账保留。",12,a.MUTED));}
  void apply(Trip.Expense e){if(enabled==null||!enabled.isChecked())return;e.payerId=ids.get(payer.getSelectedItemPosition());for(Trip.Member m:t.members)if(m.id.equals(e.payerId)&&m.archived&&(original==null||!m.id.equals(original.payerId)))throw new IllegalArgumentException("已停用成员不能作为新付款人");ArrayList<String> chosen=new ArrayList<>();for(Map.Entry<String,CheckBox> p:participants.entrySet())if(p.getValue().isChecked())chosen.add(p.getKey());e.shares.putAll(AaLedger.allocation(e.amount,chosen,original));}
  void save(Bundle b){if(enabled==null)return;b.putBoolean("finance.aa",enabled.isChecked());b.putString("finance.payer",ids.get(payer.getSelectedItemPosition()));ArrayList<String> selected=new ArrayList<>();for(Map.Entry<String,CheckBox> p:participants.entrySet())if(p.getValue().isChecked())selected.add(p.getKey());b.putStringArrayList("finance.participants",selected);}
  void restore(Bundle b){if(enabled==null||!b.containsKey("finance.aa"))return;enabled.setChecked(b.getBoolean("finance.aa"));int i=ids.indexOf(b.getString("finance.payer"));if(i>=0)payer.setSelection(i);ArrayList<String> selected=b.getStringArrayList("finance.participants");if(selected!=null)for(Map.Entry<String,CheckBox> p:participants.entrySet())p.getValue().setChecked(selected.contains(p.getKey()));}
 }
}
