package cn.lvxu.travel;

import android.content.Context;
import org.json.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.*;
import java.util.zip.*;

/** Complete, portable archive of trips, media and non-secret preferences. */
public final class BackupArchive {
    public static final long MAX_ARCHIVE=256L*1024*1024, MAX_ENTRY=64L*1024*1024;private static final int MAX_FILES=2000;
    private BackupArchive(){}
    public static void write(Context c,List<Trip> trips,AppPrefs prefs,OutputStream target)throws Exception {
        LinkedHashMap<String,String> hashes=new LinkedHashMap<>();ByteArrayOutputStream trip=new ByteArrayOutputStream();trip.write(TripStore.encode(trips).getBytes(StandardCharsets.UTF_8));
        try(ZipOutputStream z=new ZipOutputStream(new BufferedOutputStream(new LimitedOutputStream(target,MAX_ARCHIVE)))){put(z,"trips.json",trip.toByteArray(),hashes);put(z,"preferences.json",prefs.exportJson().toString(2).getBytes(StandardCharsets.UTF_8),hashes);for(String path:referencedMedia(trips,prefs))addReferenced(z,c,path,hashes);JSONObject manifest=new JSONObject().put("format",1).put("createdAt",System.currentTimeMillis());JSONObject files=new JSONObject();for(Map.Entry<String,String> e:hashes.entrySet())files.put(e.getKey(),e.getValue());manifest.put("sha256",files);putRaw(z,"manifest.json",manifest.toString(2).getBytes(StandardCharsets.UTF_8));}
    }
    public static int restore(Context c,InputStream source,TripStore store,List<Trip> existing,AppPrefs prefs)throws Exception {
        File stage=new File(c.getCacheDir(),"restore-"+UUID.randomUUID());if(!stage.mkdirs())throw new IOException("无法准备恢复目录");long total=0;try{byte[] buf=new byte[8192];HashSet<String> seen=new HashSet<>();int fileCount=0;try(ZipInputStream z=new ZipInputStream(new BufferedInputStream(source))){for(ZipEntry e;(e=z.getNextEntry())!=null;){String n=clean(e.getName());if(e.isDirectory())continue;if(!seen.add(n))throw new IOException("备份包含重复条目："+n);if(++fileCount>MAX_FILES)throw new IOException("备份文件数量过多");File out=new File(stage,n);if(!out.getCanonicalPath().startsWith(stage.getCanonicalPath()+File.separator))throw new IOException("备份路径无效");File parent=out.getParentFile();if(parent!=null&&!parent.mkdirs()&&!parent.isDirectory())throw new IOException("无法创建恢复目录");long entry=0;try(OutputStream w=new FileOutputStream(out)){for(int r;(r=z.read(buf))!=-1;){entry+=r;total+=r;if(entry>MAX_ENTRY||total>MAX_ARCHIVE)throw new IOException("备份文件过大");w.write(buf,0,r);}}}}
            File mf=new File(stage,"manifest.json"),tf=new File(stage,"trips.json");if(!mf.isFile()||!tf.isFile())throw new IOException("备份内容不完整");JSONObject manifest=new JSONObject(read(mf,2*1024*1024));if(manifest.getInt("format")!=1)throw new IOException("不支持此备份版本");JSONObject expected=manifest.getJSONObject("sha256");Iterator<String> keys=expected.keys();while(keys.hasNext()){String n=clean(keys.next());File f=new File(stage,n);if(!f.isFile()||!expected.getString(n).equals(hex(f)))throw new IOException("备份校验失败："+n);}validateFileSet(stage,stage,expected);
            ArrayList<Trip> imported=TripStore.decode(read(tf,16*1024*1024));if(existing.size()+imported.size()>100)throw new IOException("合并后旅行超过 100 个");HashSet<String> ids=new HashSet<>();for(Trip t:existing)ids.add(t.id);for(Trip t:imported)if(!ids.add(t.id)){t.id=UUID.randomUUID().toString();ids.add(t.id);}ArrayList<Trip> merged=new ArrayList<>(existing);merged.addAll(imported);
            File incoming=new File(stage,"media"),dest=new File(c.getFilesDir(),"media");validateMediaConflicts(incoming,dest);validateTripMedia(imported,incoming,dest);JSONObject importedPrefs=null;File pf=new File(stage,"preferences.json");if(pf.isFile()){importedPrefs=new JSONObject(read(pf,2*1024*1024));validatePreferenceMedia(importedPrefs,incoming,dest);validatePreferences(importedPrefs);}copyTree(incoming,incoming,dest);store.save(merged);if(importedPrefs!=null)prefs.importJson(importedPrefs);return imported.size();
        }finally{deleteTree(stage);}
    }
    private static LinkedHashSet<String> referencedMedia(List<Trip> trips,AppPrefs prefs){LinkedHashSet<String> out=new LinkedHashSet<>();addPath(out,prefs.avatar());addPath(out,prefs.background());for(Trip t:trips){for(Trip.Stop s:t.stops){addPath(out,s.previewPhoto);for(String x:s.notePhotos)addPath(out,x);}for(Trip.Item i:t.items)addPath(out,i.photo);for(Trip.Checkin c:t.checkins){addPath(out,c.photo);addPath(out,c.card);for(String x:c.groupPhotos)addPath(out,x);for(String x:c.sceneryPhotos)addPath(out,x);}}return out;}
    private static void addPath(Set<String> out,String path){if(path!=null&&!path.isEmpty())out.add(path.replace('\\','/'));}
    private static void addReferenced(ZipOutputStream z,Context c,String path,Map<String,String> hashes)throws Exception {if(!path.startsWith("media/")||path.startsWith("/")||path.contains("../")||path.contains(":")||path.endsWith("/"))throw new IOException("引用的媒体路径无效");File root=new File(c.getFilesDir(),"media").getCanonicalFile(),file=new File(c.getFilesDir(),path).getCanonicalFile();if(!file.getPath().startsWith(root.getPath()+File.separator)||!file.isFile())throw new IOException("引用的照片文件缺失："+path);if(file.length()>MAX_ENTRY)throw new IOException("媒体文件过大："+path);put(z,path,java.nio.file.Files.readAllBytes(file.toPath()),hashes);}
    private static void put(ZipOutputStream z,String n,byte[] b,Map<String,String> hashes)throws Exception {if(hashes.size()>=MAX_FILES-1)throw new IOException("备份文件数量过多");putRaw(z,n,b);hashes.put(n,hex(b));}
    private static void putRaw(ZipOutputStream z,String n,byte[] b)throws IOException {z.putNextEntry(new ZipEntry(n));z.write(b);z.closeEntry();}
    private static String clean(String n)throws IOException {if(n==null||n.startsWith("/")||n.contains("\\")||n.contains("../")||n.equals("..")||n.contains(":"))throw new IOException("备份路径无效");return n;}
    private static String read(File f,int max)throws IOException {if(f.length()>max)throw new IOException("备份条目过大");return new String(java.nio.file.Files.readAllBytes(f.toPath()),StandardCharsets.UTF_8);}
    private static String hex(File f)throws Exception {try(InputStream in=new FileInputStream(f)){MessageDigest d=MessageDigest.getInstance("SHA-256");byte[] b=new byte[8192];for(int n;(n=in.read(b))!=-1;)d.update(b,0,n);return hexDigest(d.digest());}}
    private static String hex(byte[] b)throws Exception {return hexDigest(MessageDigest.getInstance("SHA-256").digest(b));}
    private static String hexDigest(byte[] b){StringBuilder s=new StringBuilder();for(byte x:b)s.append(String.format(Locale.ROOT,"%02x",x));return s.toString();}
    private static void validateMediaConflicts(File root,File dest)throws Exception {File[] fs=root.listFiles();if(fs==null)return;for(File x:fs){File d=new File(dest,x.getName());if(x.isDirectory())validateMediaConflicts(x,d);else if(d.exists()&&!hex(x).equals(hex(d)))throw new IOException("媒体文件名冲突，请保留现有数据后重试");}}
    private static void validateFileSet(File root,File dir,JSONObject expected)throws Exception {File[] fs=dir.listFiles();if(fs==null)return;for(File f:fs){if(f.isDirectory())validateFileSet(root,f,expected);else{String rel=root.toPath().relativize(f.toPath()).toString().replace('\\','/');if(!"manifest.json".equals(rel)&&!expected.has(rel))throw new IOException("备份包含未登记文件："+rel);}}}
    private static void validatePreferenceMedia(JSONObject p,File incoming,File existing)throws Exception {for(String key:new String[]{"avatar","background"}){String rel=p.optString(key,"");if(rel.isEmpty())continue;if(!rel.startsWith("media/")||rel.contains("..")||rel.contains("\\")||rel.contains(":"))throw new IOException("偏好中的媒体路径无效");rel=rel.substring(6);File a=new File(incoming,rel).getCanonicalFile(),b=new File(existing,rel).getCanonicalFile();if(!a.getPath().startsWith(incoming.getCanonicalPath()+File.separator)&&!b.getPath().startsWith(existing.getCanonicalPath()+File.separator))throw new IOException("偏好中的媒体路径无效");if(!a.isFile()&&!b.isFile())throw new IOException("头像或背景文件缺失");}}
    private static void validateTripMedia(List<Trip> trips,File incoming,File existing)throws Exception {for(Trip t:trips){for(Trip.Stop s:t.stops){validateMediaPath(s.previewPhoto,incoming,existing);for(String x:s.notePhotos)validateMediaPath(x,incoming,existing);}for(Trip.Item i:t.items)validateMediaPath(i.photo,incoming,existing);for(Trip.Checkin x:t.checkins){validateMediaPath(x.photo,incoming,existing);validateMediaPath(x.card,incoming,existing);for(String path:x.groupPhotos)validateMediaPath(path,incoming,existing);for(String path:x.sceneryPhotos)validateMediaPath(path,incoming,existing);}}}
    private static void validateMediaPath(String path,File incoming,File existing)throws Exception {if(path==null||path.isEmpty())return;if(!path.startsWith("media/")||path.contains("..")||path.contains("\\")||path.contains(":"))throw new IOException("旅行中的媒体路径无效");String rel=path.substring(6);File a=new File(incoming,rel).getCanonicalFile(),b=new File(existing,rel).getCanonicalFile();String ia=incoming.getCanonicalPath()+File.separator,ib=existing.getCanonicalPath()+File.separator;if(!a.getPath().startsWith(ia)||!b.getPath().startsWith(ib))throw new IOException("旅行中的媒体路径无效");if(!a.isFile()&&!b.isFile())throw new IOException("旅行照片文件缺失");}
    private static void validatePreferences(JSONObject p)throws Exception {JSONArray n=p.optJSONArray("nav");if(n!=null){if(n.length()>20)throw new IOException("偏好内容无效");for(int i=0;i<n.length();i++){if(!(n.opt(i) instanceof JSONObject))throw new IOException("偏好内容无效");String id=n.getJSONObject(i).optString("id","");if(!Arrays.asList("home","itinerary","budget","checklist","checkin").contains(id))throw new IOException("偏好中的底栏项目无效");}}}
    private static void copyTree(File root,File f,File dest)throws IOException {File[] fs=f.listFiles();if(fs==null)return;if(!dest.exists()&&!dest.mkdirs())throw new IOException("无法恢复媒体");for(File x:fs){File d=new File(dest,x.getName());if(x.isDirectory())copyTree(root,x,d);else if(!d.exists())java.nio.file.Files.copy(x.toPath(),d.toPath());}}
    private static void deleteTree(File f){File[] fs=f.listFiles();if(fs!=null)for(File x:fs)deleteTree(x);f.delete();}
    private static final class LimitedOutputStream extends FilterOutputStream {long count,max;LimitedOutputStream(OutputStream out,long max){super(out);this.max=max;}public void write(int b)throws IOException{ensure(1);out.write(b);count++;}public void write(byte[] b,int off,int len)throws IOException{ensure(len);out.write(b,off,len);count+=len;}private void ensure(int n)throws IOException{if(n<0||count+n>max)throw new IOException("备份文件过大");}}
}
