package cn.lvxu.travel;
import android.graphics.*;import android.text.InputType;import android.widget.*;import java.util.*;

final class ChecklistUi {
 private final MainActivity a;private String selected;
 ChecklistUi(MainActivity a){this.a=a;}
 void show(){Trip t=a.active;t.normalize();if(t.list(selected)==null)selected=t.lists.get(0).id;Trip.Checklist list=t.list(selected);a.tripLabel();int done=0,total=0;for(Trip.Item i:t.items)if(i.listId.equals(selected)){total++;if(i.done)done++;}a.heading(list.name,done+" / "+total+" 项已准备好");HorizontalScrollView hs=new HorizontalScrollView(a);LinearLayout tabs=a.row();for(Trip.Checklist l:t.lists)tabs.addView(a.action(l.name,l.id.equals(selected),()->{selected=l.id;a.render();}));tabs.addView(a.action("＋ 清单",false,()->listEditor(null)));hs.addView(tabs);a.body.addView(hs);a.space(a.body,16);for(Trip.Item i:new ArrayList<>(t.items))if(i.listId.equals(selected))itemCard(i);a.pair(a.body,a.action("＋ 添加项目",true,()->itemEditor(null)),a.action("编辑清单",false,()->listEditor(list)));}
 private void itemCard(Trip.Item i){LinearLayout c=a.card(a.body),r=a.row();CheckBox cb=new CheckBox(a);cb.setText(i.name);cb.setChecked(i.done);cb.setTextColor(i.done?a.MUTED:a.INK);if(i.done)cb.setPaintFlags(cb.getPaintFlags()|Paint.STRIKE_THRU_TEXT_FLAG);r.addView(cb,new LinearLayout.LayoutParams(0,-2,1));r.addView(a.action("编辑",false,()->itemEditor(i)));c.addView(r);c.addView(a.text("重要性："+i.importance,12,a.MUTED));if(!i.note.isEmpty()){a.space(c,6);c.addView(a.text(i.note,13,a.MUTED));}if(!i.photo.isEmpty()){try{java.io.File file=a.mediaFile(i.photo);if(file!=null&&file.isFile()){a.space(c,8);ImageView image=new ImageView(a);image.setAdjustViewBounds(true);image.setMaxHeight(a.dp(180));image.setImageURI(android.net.Uri.fromFile(file));c.addView(image);}}catch(IllegalArgumentException ignored){}}for(Map.Entry<String,String> e:i.attributes.entrySet())c.addView(a.text(e.getKey()+"："+e.getValue(),12,a.MUTED));cb.setOnCheckedChangeListener((v,b)->{i.done=b;a.changed();});}
 private void itemEditor(Trip.Item old){Trip t=a.active;String listId=selected;if(old==null&&t.items.size()>=5000){a.toast("清单项目数量已达上限");return;}LinearLayout f=a.col();EditText name=a.field(f,"项目名称",old==null?"":old.name,1),note=a.field(f,"备注",old==null?"":old.note,InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE),attrs=a.field(f,"自定义字段（每行 键=值）",old==null?"":format(old.attributes),InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE);Spinner importance=a.select(f,"重要程度",new String[]{"普通","重要","紧急"},old==null?"普通":old.importance);String[] photoPath={old==null?"":old.photo};TextView status=a.text(photoPath[0].isEmpty()?"未添加照片":"已添加照片",12,a.MUTED);f.addView(status);f.addView(a.action("选择照片",false,()->a.pickImage(path->{photoPath[0]=path;status.setText("已选照片，保存项目后生效");})));a.space(f,8);f.addView(a.action("移除照片",false,()->{photoPath[0]="";status.setText("未添加照片");}));a.dialog(old==null?"添加项目":"编辑项目",f,()->{String n=a.required(name,120),notes=note.getText().toString().trim();if(notes.length()>2000)throw new IllegalArgumentException("备注最多 2000 字");LinkedHashMap<String,String> values=new LinkedHashMap<>();parse(attrs.getText().toString(),values);Trip.Item i=old==null?new Trip.Item():old;i.name=n;i.note=notes;i.importance=importance.getSelectedItem().toString();i.photo=photoPath[0];i.attributes.clear();i.attributes.putAll(values);if(old==null){i.listId=listId;t.items.add(i);}a.changed();},old==null?null:()->{t.items.remove(old);a.changed();});}
 private void listEditor(Trip.Checklist old){Trip t=a.active;if(old==null&&t.lists.size()>=100){a.toast("最多支持 100 个清单");return;}LinearLayout f=a.col();EditText name=a.field(f,"清单名称",old==null?"":old.name,1);if(old!=null)f.addView(a.text("删除清单时，项目会转移到另一个清单。",12,a.MUTED));a.dialog(old==null?"新建清单":"编辑清单",f,()->{String n=a.required(name,50);for(Trip.Checklist other:t.lists)if(other!=old&&other.name.equals(n))throw new IllegalArgumentException("清单名称已存在");Trip.Checklist l=old==null?new Trip.Checklist():old;l.name=n;if(old==null){t.lists.add(l);selected=l.id;}a.changed();},old==null?null:()->{if(t.lists.size()==1){a.toast("至少保留一个清单");return;}Trip.Checklist target=t.lists.get(0)==old?t.lists.get(1):t.lists.get(0);for(Trip.Item i:t.items)if(i.listId.equals(old.id))i.listId=target.id;t.lists.remove(old);selected=target.id;a.changed();});}
 private static String format(Map<String,String> m){StringBuilder b=new StringBuilder();for(Map.Entry<String,String> e:m.entrySet())b.append(e.getKey()).append('=').append(e.getValue()).append('\n');return b.toString();}
 private static void parse(String raw,LinkedHashMap<String,String> out){for(String line:raw.split("\\r?\\n")){if(line.trim().isEmpty())continue;int p=line.indexOf('=');if(p<1)throw new IllegalArgumentException("自定义字段请使用 键=值");String k=line.substring(0,p).trim(),v=line.substring(p+1).trim();if(k.isEmpty()||k.length()>40||v.length()>300||out.size()>=30)throw new IllegalArgumentException("自定义字段过长或过多");if(out.containsKey(k))throw new IllegalArgumentException("自定义字段名称重复");out.put(k,v);}}
}
