package cn.lvxu.travel;
import android.app.AlertDialog;
import android.graphics.Color;
import android.view.Gravity;
import android.widget.*;
import org.json.*;
import java.nio.charset.StandardCharsets;
import android.text.Editable;
import android.text.TextWatcher;
import android.view.View;
final class CityPickerUi {
 static String read(MainActivity a)throws Exception{try(java.io.InputStream in=a.getAssets().open("china-cities.json");java.io.ByteArrayOutputStream out=new java.io.ByteArrayOutputStream()){byte[] b=new byte[4096];int n;while((n=in.read(b))!=-1)out.write(b,0,n);return new String(out.toByteArray(),StandardCharsets.UTF_8);}}
 static EditText field(MainActivity a,LinearLayout form,String value){
  form.addView(a.text("目的地",13,MainActivity.MUTED));LinearLayout row=a.row();android.graphics.drawable.GradientDrawable background=a.shape(MainActivity.SURFACE,12);background.setStroke(a.dp(1),MainActivity.LINE);row.setBackground(background);
  EditText input=new EditText(a);input.setText(value);input.setTextSize(16);input.setSingleLine(true);input.setInputType(android.text.InputType.TYPE_CLASS_TEXT);input.setTextColor(MainActivity.INK);input.setHintTextColor(MainActivity.MUTED);input.setHint("选择城市，也可直接输入目的地");input.setPadding(a.dp(14),a.dp(12),0,a.dp(12));input.setBackgroundColor(Color.TRANSPARENT);row.addView(input,new LinearLayout.LayoutParams(0,-2,1));
  TextView dropdown=a.text("▾",24,MainActivity.INK);dropdown.setGravity(Gravity.CENTER);dropdown.setContentDescription("选择目的地城市");dropdown.setFocusable(true);dropdown.setOnClickListener(v->show(a,input));row.addView(dropdown,new LinearLayout.LayoutParams(a.dp(48),a.dp(48)));form.addView(row,new LinearLayout.LayoutParams(-1,-2));a.space(form,12);return input;
 }
 static void show(MainActivity a,EditText target){
  try{JSONArray data=new JSONArray(read(a));LinearLayout columns=a.row();columns.setPadding(a.dp(12),0,a.dp(12),0);LinearLayout provinces=a.col(),cities=a.col();ScrollView left=new ScrollView(a),right=new ScrollView(a);left.addView(provinces);right.addView(cities);left.setBackground(a.shape(MainActivity.PALE,12));
   int available=a.getResources().getDisplayMetrics().heightPixels-a.dp(340);int height=Math.min(a.dp(420),Math.max(a.dp(120),available));columns.addView(left,new LinearLayout.LayoutParams(0,height,2));LinearLayout.LayoutParams rightParams=new LinearLayout.LayoutParams(0,height,3);rightParams.leftMargin=a.dp(8);columns.addView(right,rightParams);
   LinearLayout body=a.col();body.setPadding(a.dp(12),0,a.dp(12),0);EditText search=a.field(body,"搜索城市或省份","",android.text.InputType.TYPE_CLASS_TEXT);search.setHint("例如：兰州、甘肃");LinearLayout shortcuts=a.col();body.addView(shortcuts);LinearLayout results=a.col();ScrollView resultScroll=new ScrollView(a);resultScroll.addView(results);resultScroll.setVisibility(View.GONE);body.addView(resultScroll,new LinearLayout.LayoutParams(-1,height));body.addView(columns);
   AlertDialog dialog=new RoundedDialogs.Builder(a).asSelection().setTitle("选择目的地").setView(body).setNegativeButton("取消",null).create();
   java.util.function.Consumer<String> choose=city->{target.setText(city);target.setSelection(city.length());remember(a,city);dialog.dismiss();};
   java.util.LinkedHashSet<String> recent=new java.util.LinkedHashSet<>();try{JSONArray history=new JSONArray(a.getSharedPreferences("city-picker-v1",0).getString("recent","[]"));for(int i=0;i<history.length();i++)recent.add(history.getString(i));}catch(Exception ignored){}
   java.util.ArrayList<String> quick=new java.util.ArrayList<>(recent);if(quick.isEmpty())java.util.Collections.addAll(quick,"北京市","上海市","广州市","成都市","兰州市");shortcuts.addView(a.text(recent.isEmpty()?"常用城市":"最近选择",12,MainActivity.MUTED));HorizontalScrollView quickScroll=new HorizontalScrollView(a);quickScroll.setHorizontalScrollBarEnabled(false);LinearLayout quickRow=a.row();for(String name:quick){TextView chip=item(a,name);chip.setOnClickListener(v->choose.accept(name));quickRow.addView(chip);}quickScroll.addView(quickRow);shortcuts.addView(quickScroll);
   final int[] selected={0};String current=target.getText().toString().trim();for(int i=0;i<data.length();i++){JSONArray names=data.getJSONObject(i).getJSONArray("cities");for(int j=0;j<names.length();j++)if(current.equals(names.getString(j)))selected[0]=i;}
   Runnable[] update={null};update[0]=()->{cities.removeAllViews();for(int i=0;i<provinces.getChildCount();i++){TextView p=(TextView)provinces.getChildAt(i);boolean active=i==selected[0];p.setSelected(active);p.setBackground(a.shape(active?MainActivity.GREEN:MainActivity.PALE,10));p.setTextColor(MainActivity.readable(active?Color.WHITE:MainActivity.INK,active?MainActivity.GREEN:MainActivity.PALE));}
    try{JSONArray names=data.getJSONObject(selected[0]).getJSONArray("cities");for(int j=0;j<names.length();j++){String city=names.getString(j);TextView item=item(a,city);item.setOnClickListener(v->choose.accept(city));cities.addView(item,new LinearLayout.LayoutParams(-1,-2));}right.scrollTo(0,0);ThemeViews.apply(columns,MainActivity.SURFACE);}catch(JSONException ignored){}
   };
   search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int start,int count,int after){}public void onTextChanged(CharSequence s,int start,int before,int count){String query=s.toString().trim();boolean searching=!query.isEmpty();columns.setVisibility(searching?View.GONE:View.VISIBLE);shortcuts.setVisibility(searching?View.GONE:View.VISIBLE);resultScroll.setVisibility(searching?View.VISIBLE:View.GONE);results.removeAllViews();if(!searching)return;try{for(int i=0;i<data.length();i++){JSONObject province=data.getJSONObject(i);String provinceName=province.getString("province");JSONArray names=province.getJSONArray("cities");for(int j=0;j<names.length();j++){String name=names.getString(j);if(name.contains(query)||provinceName.contains(query)){TextView hit=item(a,name+" · "+provinceName);hit.setContentDescription("选择城市 "+name);hit.setOnClickListener(v->choose.accept(name));results.addView(hit);}}}if(results.getChildCount()==0)results.addView(a.text("没有匹配城市，可返回表单直接输入目的地",13,MainActivity.MUTED));}catch(JSONException ignored){}}public void afterTextChanged(Editable e){}});
   for(int i=0;i<data.length();i++){final int index=i;TextView p=item(a,data.getJSONObject(i).getString("province"));p.setOnClickListener(v->{selected[0]=index;update[0].run();});provinces.addView(p,new LinearLayout.LayoutParams(-1,-2));}update[0].run();left.post(()->{if(selected[0]<provinces.getChildCount())left.scrollTo(0,provinces.getChildAt(selected[0]).getTop());});dialog.show();if(dialog.getWindow()!=null)dialog.getWindow().setSoftInputMode(android.view.WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_HIDDEN|android.view.WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);
  }catch(Exception e){a.toast("城市目录暂不可用，请直接输入目的地");}
 }
 private static void remember(MainActivity a,String city){java.util.LinkedHashSet<String> values=new java.util.LinkedHashSet<>();values.add(city);try{JSONArray old=new JSONArray(a.getSharedPreferences("city-picker-v1",0).getString("recent","[]"));for(int i=0;i<old.length()&&values.size()<6;i++)values.add(old.getString(i));}catch(Exception ignored){}a.getSharedPreferences("city-picker-v1",0).edit().putString("recent",new JSONArray(values).toString()).apply();}
 private static TextView item(MainActivity a,String text){TextView item=a.text(text,15,MainActivity.INK);item.setMinHeight(a.dp(48));item.setGravity(Gravity.CENTER_VERTICAL);item.setPadding(a.dp(12),a.dp(10),a.dp(12),a.dp(10));item.setFocusable(true);return item;}
}
