package cn.lvxu.travel;
import android.app.*;import android.graphics.*;import android.view.*;import android.widget.*;import java.time.*;import java.util.*;

final class FinanceUi {
 private final MainActivity a;private boolean line;
 private static final int[] COLORS={0xffE07A5F,0xff3D85C6,0xff8064A2,0xffD6A84B,0xff4F9D69,0xff829399};
 FinanceUi(MainActivity a){this.a=a;}
 void show(){Trip t=a.active;t.normalize();a.tripLabel();a.heading("花得明白，玩得自在。","旅行账本 · 金额统一以人民币记录");LinearLayout c=a.card(a.body);c.setBackground(a.shape(a.GREEN,20));c.addView(a.text("实际支出",13,0xffE4F0E5));a.space(c,10);c.addView(a.bold("¥ "+Trip.money(t.spent()),36,Color.WHITE));long remain=t.budget-t.spent();a.space(c,12);c.addView(a.text((remain>=0?"剩余预算 ¥":"已超预算 ¥")+Trip.money(Math.abs(remain)),14,Color.WHITE));a.space(a.body,10);a.pair(a.body,a.action("＋ 记一笔",true,()->expense(null)),a.action("管理分类",false,this::categories));a.space(a.body,14);a.pair(a.body,a.action("分类占比",!line,()->{line=false;a.render();}),a.action("日期趋势",line,()->{line=true;a.render();}));a.body.addView(new Chart(a,t,line),new LinearLayout.LayoutParams(-1,a.dp(220)));if(!line&&t.spent()>0){for(Trip.Category cat:t.categories){long sum=0;for(Trip.Expense e:t.expenses)if(cat.id.equals(e.categoryId))sum+=e.amount;if(sum>0)a.body.addView(a.text("● "+cat.name+"    ¥"+Trip.money(sum)+"    "+String.format(Locale.ROOT,"%.1f%%",sum*100d/t.spent()),13,cat.color));}}else if(line&&!t.expenses.isEmpty()){a.body.addView(a.text("按支出日期汇总；横轴为实际日期，点为当天合计。",12,a.MUTED));}a.section("账单明细");if(t.expenses.isEmpty())a.body.addView(a.text("还没有实际支出。",13,a.MUTED));ArrayList<Trip.Expense> es=new ArrayList<>(t.expenses);es.sort((x,y)->y.occurredAt.compareTo(x.occurredAt));for(Trip.Expense e:es){LinearLayout x=a.card(a.body);x.addView(a.bold(e.name+"    ¥"+Trip.money(e.amount),17,a.INK));a.space(x,6);x.addView(a.text(e.category+" · "+e.occurredAt.replace('T',' '),12,a.MUTED));x.setOnClickListener(v->expense(e));}}
 private void expense(Trip.Expense old){if(old==null&&a.active.expenses.size()>=5000){a.toast("账单数量已达上限");return;}Trip t=a.active;LinearLayout f=a.col();EditText name=a.field(f,"账单名称",old==null?"":old.name,1),amount=a.field(f,"实际金额（人民币）",old==null?"":Trip.money(old.amount),8194),when=a.field(f,"日期时间",old==null?LocalDateTime.now().withSecond(0).withNano(0).toString():old.occurredAt,1);when.setFocusable(false);when.setOnClickListener(v->{LocalDateTime current=LocalDateTime.parse(when.getText().toString());new DatePickerDialog(a,(picker,y,m,d)->new TimePickerDialog(a,(clock,h,min)->when.setText(LocalDateTime.of(y,m+1,d,h,min).toString()),current.getHour(),current.getMinute(),true).show(),current.getYear(),current.getMonthValue()-1,current.getDayOfMonth()).show();});String[] names=new String[t.categories.size()];for(int i=0;i<names.length;i++)names[i]=t.categories.get(i).name;Spinner cat=a.select(f,"支出分类",names,old==null?names[0]:old.category);a.dialog(old==null?"记录支出":"编辑支出",f,()->{String n=a.required(name,120);long value=Trip.cents(amount.getText().toString());String time=LocalDateTime.parse(when.getText().toString().trim()).withSecond(0).withNano(0).toString();Trip.Expense e=old==null?new Trip.Expense():old;e.name=n;e.amount=value;e.occurredAt=time;Trip.Category c=t.categories.get(cat.getSelectedItemPosition());e.categoryId=c.id;e.category=c.name;if(old==null)t.expenses.add(e);a.changed();},old==null?null:()->{t.expenses.remove(old);a.changed();});}
 private void categories(){Trip t=a.active;String[] options=new String[t.categories.size()+1];options[0]="＋ 新建分类";for(int i=0;i<t.categories.size();i++)options[i+1]=t.categories.get(i).name;new AlertDialog.Builder(a).setTitle("支出分类").setItems(options,(d,i)->{if(i==0)category(null);else category(t.categories.get(i-1));}).show();}
 private void category(Trip.Category old){Trip t=a.active;if(old==null&&t.categories.size()>=100){a.toast("最多支持 100 个分类");return;}LinearLayout f=a.col();EditText name=a.field(f,"分类名称",old==null?"":old.name,1);String[] names={"珊瑚","蓝色","紫色","金色","绿色","灰色"};int selected=4;if(old!=null)for(int i=0;i<COLORS.length;i++)if(COLORS[i]==old.color)selected=i;Spinner color=a.select(f,"颜色",names,names[selected]);a.dialog(old==null?"新建分类":"编辑分类",f,()->{String n=a.required(name,30);for(Trip.Category c:t.categories)if(c!=old&&c.name.equals(n))throw new IllegalArgumentException("分类名称已存在");Trip.Category c=old==null?new Trip.Category():old;c.name=n;c.color=COLORS[color.getSelectedItemPosition()];if(old==null)t.categories.add(c);else for(Trip.Expense e:t.expenses)if(c.id.equals(e.categoryId))e.category=n;a.changed();},old==null?null:()->deleteCategory(old));}
 private void deleteCategory(Trip.Category old){Trip t=a.active;if(t.categories.size()<2){a.toast("至少保留一个分类");return;}ArrayList<Trip.Category> rest=new ArrayList<>(t.categories);rest.remove(old);String[] n=new String[rest.size()];for(int i=0;i<n.length;i++)n[i]=rest.get(i).name;new AlertDialog.Builder(a).setTitle("选择分类接收原账单").setItems(n,(d,i)->{t.deleteCategory(old.id,rest.get(i).id);a.changed();}).setNegativeButton("取消",null).show();}
 static final class Chart extends View {
  final Paint p=new Paint(3);final Trip t;final boolean line;final MainActivity a;
  Chart(MainActivity a,Trip t,boolean line){super(a);this.a=a;this.t=t;this.line=line;setContentDescription(line?"按日期的支出趋势图":"按分类的支出占比图");}
  protected void onDraw(Canvas c){super.onDraw(c);float w=getWidth(),h=getHeight();p.setTextSize(a.dp(12));p.setColor(a.MUTED);if(t.expenses.isEmpty()||(!line&&t.spent()==0)){p.setTextAlign(Paint.Align.CENTER);c.drawText("记录支出后，这里会显示图表",w/2,h/2,p);return;}
   if(!line){long total=t.spent();float at=-90,r=Math.min(w,h)*.4f,cx=w/2,cy=h/2;for(Trip.Category cat:t.categories){long n=0;for(Trip.Expense e:t.expenses)if(cat.id.equals(e.categoryId))n+=e.amount;if(n==0)continue;p.setColor(cat.color);float sweep=(float)(360d*n/total);c.drawArc(cx-r,cy-r,cx+r,cy+r,at,sweep,true,p);at+=sweep;}p.setColor(a.BG);c.drawCircle(cx,cy,r*.57f,p);p.setTextAlign(Paint.Align.CENTER);p.setColor(a.INK);c.drawText("分类占比",cx,cy+a.dp(4),p);return;}
   TreeMap<LocalDate,Long> m=new TreeMap<>();for(Trip.Expense e:t.expenses){LocalDate d=LocalDateTime.parse(e.occurredAt).toLocalDate();m.put(d,m.getOrDefault(d,0L)+e.amount);}long max=1;for(long n:m.values())max=Math.max(max,n);float left=a.dp(58),right=w-a.dp(12),top=a.dp(24),bottom=h-a.dp(35);p.setStrokeWidth(a.dp(1));p.setColor(a.LINE);c.drawLine(left,top,left,bottom,p);c.drawLine(left,bottom,right,bottom,p);p.setColor(a.MUTED);p.setTextAlign(Paint.Align.RIGHT);c.drawText("¥"+compact(max),left-a.dp(5),top+a.dp(4),p);c.drawText("0",left-a.dp(5),bottom,p);p.setTextAlign(Paint.Align.LEFT);c.drawText(m.firstKey().toString().substring(5),left,bottom+a.dp(23),p);if(m.size()>1){p.setTextAlign(Paint.Align.RIGHT);c.drawText(m.lastKey().toString().substring(5),right,bottom+a.dp(23),p);}long first=m.firstKey().toEpochDay(),span=Math.max(1,m.lastKey().toEpochDay()-first);Path path=new Path();int index=0;ArrayList<float[]> dots=new ArrayList<>();for(Map.Entry<LocalDate,Long> e:m.entrySet()){float x=m.size()==1?(left+right)/2:left+(right-left)*(e.getKey().toEpochDay()-first)/span,y=bottom-(bottom-top)*e.getValue()/max;dots.add(new float[]{x,y});if(index++==0)path.moveTo(x,y);else path.lineTo(x,y);}p.setColor(a.GREEN);p.setStrokeWidth(a.dp(2));p.setStyle(Paint.Style.STROKE);c.drawPath(path,p);p.setStyle(Paint.Style.FILL);for(float[] dot:dots)c.drawCircle(dot[0],dot[1],a.dp(4),p);
  }
  private String compact(long cents){double yuan=cents/100d;return yuan>=10000?String.format(Locale.ROOT,"%.1f万",yuan/10000):Trip.money(cents);}
 }
}
