package cn.lvxu.travel;

import android.app.*;
import android.os.Bundle;
import android.content.*;
import android.net.Uri;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.view.*;
import android.widget.*;
import android.text.InputType;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.io.*;
import java.nio.charset.StandardCharsets;

public class MainActivity extends Activity {
    static final int BG=0xffF6F5F0, INK=0xff233C34, GREEN=0xff23644F, MUTED=0xff7D867E, LINE=0xffE2E6DC, PALE=0xffE7EDDF, ORANGE=0xffAC592F;
    ArrayList<Trip> trips=new ArrayList<>();TripStore store;Trip active;int page=0,day=0;LinearLayout root,body;boolean loadFailed=false;
    @Override public void onCreate(Bundle state){super.onCreate(state);store=new TripStore(this);try{if(store.exists())trips=store.read();else{trips.add(Trip.demo());store.save(trips);}}catch(Exception e){loadFailed=true;new AlertDialog.Builder(this).setTitle("无法读取本地行程").setMessage("原文件已保留。请重启应用重试；若有备份，可通过导入恢复。").setPositiveButton("知道了",null).show();}if(!trips.isEmpty())active=trips.get(0);if(state!=null){page=state.getInt("page");day=state.getInt("day");for(Trip t:trips)if(t.id.equals(state.getString("trip")))active=t;}render();}
    @Override public void onSaveInstanceState(Bundle b){super.onSaveInstanceState(b);b.putInt("page",page);b.putInt("day",day);if(active!=null)b.putString("trip",active.id);}
    int dp(float n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
    GradientDrawable shape(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
    LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(1);return l;}
    LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(0);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
    TextView text(String s,int size,int color){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(color);v.setIncludeFontPadding(false);v.setLineSpacing(dp(3),1);return v;}
    TextView bold(String s,int size,int color){TextView t=text(s,size,color);t.setTypeface(null,Typeface.BOLD);return t;}
    void space(LinearLayout l,int h){View v=new View(this);l.addView(v,new LinearLayout.LayoutParams(1,dp(h)));}
    void pad(View v,int p){v.setPadding(dp(p),dp(p),dp(p),dp(p));}
    TextView action(String label,boolean primary,Runnable fn){TextView v=bold(label,14,primary?Color.WHITE:GREEN);v.setGravity(Gravity.CENTER);v.setMinHeight(dp(48));v.setPadding(dp(14),dp(10),dp(14),dp(10));v.setBackground(shape(primary?GREEN:PALE,14));v.setContentDescription(label);v.setFocusable(true);v.setOnClickListener(w->fn.run());return v;}
    void pair(LinearLayout l,View left,View right){LinearLayout r=row();r.addView(left,new LinearLayout.LayoutParams(0,-2,1));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);p.leftMargin=dp(10);r.addView(right,p);l.addView(r);}
    LinearLayout card(LinearLayout parent){LinearLayout c=col();pad(c,18);c.setBackground(shape(Color.WHITE,20));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(12);parent.addView(c,p);return c;}
    void heading(String label,String caption){body.addView(bold(label,28,INK));space(body,8);body.addView(text(caption,13,MUTED));space(body,22);}
    void section(String title){space(body,12);body.addView(bold(title,18,INK));space(body,12);}
    void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
    boolean save(){if(loadFailed){toast("本地读取失败，暂不能修改。请先恢复备份。");return false;}try{store.save(trips);return true;}catch(Exception e){toast("保存失败，请检查手机可用存储空间。此次修改尚未保存。");return false;}}
    void changed(){if(!save()&&!loadFailed){try{String selected=active==null?"":active.id;trips=store.read();active=trips.isEmpty()?null:trips.get(0);for(Trip t:trips)if(t.id.equals(selected))active=t;}catch(Exception e){loadFailed=true;}}render();}
    void render(){
        root=col();root.setBackgroundColor(BG);setContentView(root);
        if(android.os.Build.VERSION.SDK_INT>=30)root.setOnApplyWindowInsetsListener((v,in)->{android.graphics.Insets bars=in.getInsets(android.view.WindowInsets.Type.systemBars());v.setPadding(bars.left,bars.top,bars.right,bars.bottom);return in;});
        LinearLayout top=row();top.setPadding(dp(22),dp(15),dp(22),dp(12));top.addView(bold(getString(R.string.app_name),22,GREEN),new LinearLayout.LayoutParams(0,-2,1));TextView tools=action("备份",false,this::backupMenu);top.addView(tools);root.addView(top);
        ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);body=col();body.setPadding(dp(22),dp(12),dp(22),dp(24));scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        if(page==0)home();else if(active==null){heading("下一程，从这里开始","新建一个旅行，慢慢填满期待。");body.addView(action("＋ 创建旅行",true,()->tripEditor(null)));}else{day=Math.max(0,Math.min(day,active.days-1));if(page==1)itinerary();if(page==2)budget();if(page==3)checklist();}
        LinearLayout nav=row();nav.setPadding(dp(12),dp(8),dp(12),dp(10));nav.setBackgroundColor(Color.WHITE);String[] labels={"旅行","行程","预算","清单"};String[] icons={"◈","☷","¥","✓"};for(int k=0;k<4;k++){final int p=k;LinearLayout n=col();n.setGravity(Gravity.CENTER);n.setPadding(0,dp(7),0,dp(7));n.setBackground(shape(page==k?PALE:Color.WHITE,14));n.addView(bold(icons[k],22,page==k?GREEN:MUTED),new LinearLayout.LayoutParams(-2,-2));space(n,4);n.addView(text(labels[k],12,page==k?GREEN:MUTED),new LinearLayout.LayoutParams(-2,-2));n.setContentDescription(labels[k]);n.setFocusable(true);n.setOnClickListener(v->{page=p;render();});nav.addView(n,new LinearLayout.LayoutParams(0,-2,1));}root.addView(nav);
    }
    void home(){
        heading("把期待，排进日历。","YOUR NEXT CHAPTER  /  每一程，都从容");
        LinearLayout hero=col();hero.setBackground(shape(PALE,24));hero.setClipToOutline(true);hero.addView(new Landscape(this),new LinearLayout.LayoutParams(-1,dp(155)));LinearLayout copy=col();pad(copy,20);copy.addView(bold("去山野，也去日常之外",22,INK));space(copy,8);copy.addView(text("给旅途一点计划，给自己一点自由。",13,GREEN));space(copy,16);copy.addView(action("＋ 开始一段旅行",true,()->tripEditor(null)));hero.addView(copy);body.addView(hero);section("我的旅行  ·  "+trips.size());
        if(trips.isEmpty())body.addView(text("还没有行程。点上方按钮创建第一段旅行。",14,MUTED));
        for(Trip t:trips){LinearLayout c=card(body);c.addView(text(t.city+"  /  "+t.days+" DAYS",12,GREEN));space(c,10);c.addView(bold(t.title,20,INK));space(c,8);c.addView(text(t.start+" 出发 · "+t.stops.size()+" 个地点",13,MUTED));space(c,16);pair(c,action("打开行程 →",true,()->{active=t;day=0;page=1;render();}),action("编辑旅行",false,()->tripEditor(t)));}
        space(body,8);body.addView(text("离线保存在此设备 · 建议定期导出备份\n初始杭州行程为示例，费用和安排仅供编辑体验。",12,MUTED));
    }
    void tripLabel(){TextView v=text(active.title+"  ▾",13,GREEN);v.setPadding(0,dp(8),0,dp(16));v.setOnClickListener(w->{String[] names=new String[trips.size()];for(int i=0;i<names.length;i++)names[i]=trips.get(i).title;new AlertDialog.Builder(this).setTitle("切换旅行").setItems(names,(d,i)->{active=trips.get(i);day=0;render();}).show();});v.setContentDescription("切换旅行");body.addView(v);}
    void itinerary(){
        tripLabel();heading("每日行程","按时间串起风景，也留一点空白。");
        HorizontalScrollView hs=new HorizontalScrollView(this);hs.setHorizontalScrollBarEnabled(false);LinearLayout ds=row();for(int i=0;i<active.days;i++){final int index=i;TextView v=action("D"+(i+1)+"\n"+LocalDate.parse(active.start).plusDays(i).format(DateTimeFormatter.ofPattern("M/d")),day==i,()->{day=index;render();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(dp(76),-2);p.rightMargin=dp(8);ds.addView(v,p);}hs.addView(ds);body.addView(hs);hs.post(()->hs.scrollTo(dp(Math.max(0,day-1)*84),0));space(body,20);
        ArrayList<Trip.Stop> list=active.onDay(day);long cost=0;for(Trip.Stop s:list)cost+=s.cost;body.addView(text(list.size()+" 个地点    ·    预计 ¥"+Trip.money(cost),13,MUTED));space(body,16);
        if(list.isEmpty()){LinearLayout c=card(body);c.addView(bold("今天，想去哪里？",20,INK));space(c,8);c.addView(text("添加景点、餐厅或住宿，按开始时间自动排序。",14,MUTED));}
        for(int i=0;i<list.size();i++){Trip.Stop s=list.get(i);LinearLayout c=card(body);LinearLayout r=row();r.addView(bold(String.format(Locale.ROOT,"%02d",i+1),24,GREEN));TextView time=bold(s.time+"  ·  "+s.duration+" 分钟",14,INK);time.setPadding(dp(16),0,0,0);r.addView(time);c.addView(r);space(c,14);c.addView(bold(s.name,20,INK));space(c,8);c.addView(text("抵达："+s.mode+"   /   预计 ¥"+Trip.money(s.cost),13,MUTED));if(!s.note.isEmpty()){space(c,10);c.addView(text(s.note,14,MUTED));}if(i>0){Trip.Stop prev=list.get(i-1);if(java.time.LocalTime.parse(prev.time).toSecondOfDay()/60+prev.duration>java.time.LocalTime.parse(s.time).toSecondOfDay()/60){space(c,8);c.addView(text("时间与上一安排重叠，请检查。",12,ORANGE));}}space(c,16);pair(c,action("地图搜索 ↗",false,()->map(s)),action("编辑地点",false,()->stopEditor(s)));}
        body.addView(action("＋ 添加当天地点",true,()->stopEditor(null)));space(body,12);body.addView(action("分享文字行程",false,this::share));space(body,12);body.addView(text("地图搜索将打开外部地图；交通方式为手动记录。",12,MUTED));
    }
    void budget(){
        tripLabel();heading("花得明白，玩得自在。","旅行账本  /  金额统一以人民币记录");
        LinearLayout c=card(body);c.setBackground(shape(GREEN,22));c.addView(text("实际支出",13,0xffC9DFD0));space(c,12);c.addView(bold("¥ "+Trip.money(active.spent()),38,Color.WHITE));space(c,18);long remain=active.budget-active.spent();c.addView(text((remain>=0?"剩余预算  ¥ ":"已超预算  ¥ ")+Trip.money(Math.abs(remain)),15,Color.WHITE));space(c,14);ProgressBar bar=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);bar.setMax(1000);bar.setProgress(active.budget==0?(active.spent()>0?1000:0):(int)Math.min(1000,active.spent()*1000/active.budget));bar.setProgressTintList(android.content.res.ColorStateList.valueOf(0xffD5BE8F));c.addView(bar,new LinearLayout.LayoutParams(-1,dp(8)));space(c,12);c.addView(text("总预算 ¥"+Trip.money(active.budget)+"  ·  地点预计 ¥"+Trip.money(active.planned()),12,0xffC9DFD0));space(body,2);pair(body,action("＋ 记一笔",true,()->expenseEditor(null)),action("调整总预算",false,()->tripEditor(active)));
        section("支出分类");String[] cats={"餐饮","交通","住宿","门票","购物","其他"};for(String cat:cats){long total=0;for(Trip.Expense e:active.expenses)if(e.category.equals(cat))total+=e.amount;LinearLayout r=row();r.setPadding(0,dp(8),0,dp(8));r.addView(text(cat,14,INK),new LinearLayout.LayoutParams(0,-2,1));r.addView(bold("¥ "+Trip.money(total),15,INK));body.addView(r);}
        section("账单明细");if(active.expenses.isEmpty())body.addView(text("还没有实际支出。景点预计费用不会自动记账。",13,MUTED));for(Trip.Expense e:active.expenses){LinearLayout x=card(body);x.addView(bold(e.name+"    ¥"+Trip.money(e.amount),17,INK));space(x,8);x.addView(text(e.category+"  ·  点击编辑",12,MUTED));x.setOnClickListener(v->expenseEditor(e));}
    }
    void checklist(){tripLabel();int done=0;for(Trip.Item i:active.items)if(i.done)done++;heading("出发前，再看一眼。",done+" / "+active.items.size()+" 项已准备好");for(Trip.Item item:active.items){LinearLayout c=card(body);LinearLayout r=row();CheckBox cb=new CheckBox(this);cb.setText(item.name);cb.setTextSize(16);cb.setTextColor(item.done?MUTED:INK);cb.setChecked(item.done);if(item.done)cb.setPaintFlags(cb.getPaintFlags()|Paint.STRIKE_THRU_TEXT_FLAG);r.addView(cb,new LinearLayout.LayoutParams(0,-2,1));r.addView(action("删除",false,()->confirm("删除清单项？",()->{active.items.remove(item);changed();})));cb.setOnCheckedChangeListener((v,b)->{item.done=b;changed();});c.addView(r);}body.addView(action("＋ 添加待办 / 行李",true,()->{LinearLayout form=col();EditText name=field(form,"清单内容","",InputType.TYPE_CLASS_TEXT);dialog("添加清单",form,()->{String value=required(name,120);active.items.add(new Trip.Item(value));changed();},null);}));space(body,16);body.addView(text("行程、账本与清单均保存在本机。应用不会上传你的旅行数据。",12,MUTED));}
    EditText field(LinearLayout form,String title,String value,int type){form.addView(text(title,13,MUTED));EditText e=new EditText(this);e.setText(value);e.setTextSize(16);e.setTextColor(INK);e.setInputType(type);e.setSingleLine(type!= (InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE));form.addView(e,new LinearLayout.LayoutParams(-1,-2));space(form,12);return e;}
    Spinner select(LinearLayout f,String title,String[] options,String current){f.addView(text(title,13,MUTED));Spinner s=new Spinner(this);ArrayAdapter<String> a=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,options);s.setAdapter(a);for(int i=0;i<options.length;i++)if(options[i].equals(current))s.setSelection(i);f.addView(s,new LinearLayout.LayoutParams(-1,dp(52)));space(f,10);return s;}
    String required(EditText e,int max){String s=e.getText().toString().trim();if(s.isEmpty()||s.length()>max){e.setError("请填写 1–"+max+" 个字");throw new IllegalArgumentException("请检查填写内容");}return s;}
    int number(EditText e,int min,int max){try{int n=Integer.parseInt(e.getText().toString());if(n<min||n>max)throw new Exception();return n;}catch(Exception ex){e.setError("请输入 "+min+"–"+max);throw new IllegalArgumentException("请检查数字范围");}}
    void dialog(String title,LinearLayout form,Runnable submit,Runnable remove){pad(form,22);ScrollView sc=new ScrollView(this);sc.addView(form);AlertDialog.Builder b=new AlertDialog.Builder(this).setTitle(title).setView(sc).setNegativeButton("取消",null).setPositiveButton("保存",null);if(remove!=null)b.setNeutralButton("删除",(d,w)->confirm("确定删除？此操作不能撤销。",remove));AlertDialog dlg=b.create();dlg.setOnShowListener(v->dlg.getButton(-1).setOnClickListener(w->{if(loadFailed){toast("请先通过备份恢复数据");return;}try{submit.run();dlg.dismiss();}catch(IllegalArgumentException e){toast(e.getMessage());}}));dlg.show();}
    void confirm(String label,Runnable fn){new AlertDialog.Builder(this).setTitle(label).setNegativeButton("取消",null).setPositiveButton("确定",(d,w)->fn.run()).show();}
    void tripEditor(Trip original){
        if(original==null&&trips.size()>=100){toast("最多支持 100 个旅行");return;}LinearLayout f=col();EditText title=field(f,"旅行名称",original==null?"":original.title,1);EditText city=field(f,"目的地城市",original==null?"":original.city,1);EditText date=field(f,"出发日期",original==null?LocalDate.now().plusDays(7).toString():original.start,1);date.setFocusable(false);date.setOnClickListener(v->{LocalDate d=LocalDate.parse(date.getText().toString());new DatePickerDialog(this,(picker,y,m,dd)->date.setText(LocalDate.of(y,m+1,dd).toString()),d.getYear(),d.getMonthValue()-1,d.getDayOfMonth()).show();});EditText days=field(f,"旅行天数（1–60）",original==null?"3":""+original.days,2);EditText budget=field(f,"总预算（人民币）",original==null?"2000":Trip.money(original.budget),8194);
        dialog(original==null?"新的旅行":"编辑旅行",f,()->{String name=required(title,80),dest=required(city,80);int n=number(days,1,60);long money=Trip.cents(budget.getText().toString());if(original!=null)for(Trip.Stop s:original.stops)if(s.day>=n)throw new IllegalArgumentException("后面的天数还有地点，请先移动或删除后再缩短旅行");Trip t=original==null?new Trip():original;t.title=name;t.city=dest;t.start=date.getText().toString();t.days=n;t.budget=money;if(original==null){t.items.add(new Trip.Item("确认车票与住宿"));t.items.add(new Trip.Item("身份证 / 护照"));trips.add(t);}active=t;day=Math.min(day,n-1);changed();},original==null?null:()->{trips.remove(original);if(active==original){active=trips.isEmpty()?null:trips.get(0);day=0;}changed();});
    }
    void stopEditor(Trip.Stop original){
        if(original==null&&active.stops.size()>=1000){toast("地点数量已达上限");return;}Trip.Stop s=original==null?new Trip.Stop():original;LinearLayout f=col();EditText name=field(f,"地点名称",s.name,1);String[] days=new String[active.days];for(int i=0;i<days.length;i++)days[i]="第 "+(i+1)+" 天";Spinner chosen=select(f,"安排日期",days,days[original==null?day:s.day]);EditText time=field(f,"开始时间",s.time,1);time.setFocusable(false);time.setOnClickListener(v->{java.time.LocalTime t=java.time.LocalTime.parse(time.getText().toString());new TimePickerDialog(this,(p,h,m)->time.setText(String.format(Locale.ROOT,"%02d:%02d",h,m)),t.getHour(),t.getMinute(),true).show();});EditText duration=field(f,"停留时长（分钟）",""+s.duration,2);Spinner mode=select(f,"抵达此地点的交通方式",new String[]{"步行","地铁","公交","出租车","自驾","火车","飞机","其他"},s.mode);EditText cost=field(f,"预计费用（人民币）",Trip.money(s.cost),8194);EditText note=field(f,"备注（预约、地址等）",s.note,InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE);
        dialog(original==null?"添加地点":"编辑地点",f,()->{String n=required(name,120);int dur=number(duration,1,1440);long c=Trip.cents(cost.getText().toString());String notes=note.getText().toString().trim();if(notes.length()>2000)throw new IllegalArgumentException("备注最多 2000 字");s.name=n;s.duration=dur;s.time=time.getText().toString();s.day=chosen.getSelectedItemPosition();s.mode=mode.getSelectedItem().toString();s.cost=c;s.note=notes;if(original==null)active.stops.add(s);day=s.day;changed();},original==null?null:()->{active.stops.remove(s);changed();});
    }
    void expenseEditor(Trip.Expense original){if(original==null&&active.expenses.size()>=5000){toast("账单数量已达上限");return;}LinearLayout f=col();EditText name=field(f,"账单名称",original==null?"":original.name,1);EditText amount=field(f,"实际金额（人民币）",original==null?"":Trip.money(original.amount),8194);Spinner cat=select(f,"支出分类",new String[]{"餐饮","交通","住宿","门票","购物","其他"},original==null?"餐饮":original.category);dialog("记录支出",f,()->{String n=required(name,120);long a=Trip.cents(amount.getText().toString());Trip.Expense e=original==null?new Trip.Expense():original;e.name=n;e.amount=a;e.category=cat.getSelectedItem().toString();if(original==null)active.expenses.add(e);changed();},original==null?null:()->{active.expenses.remove(original);changed();});}
    void map(Trip.Stop s){String q=active.city+" "+s.name;try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("geo:0,0?q="+Uri.encode(q))));}catch(ActivityNotFoundException e){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://uri.amap.com/search?keyword="+Uri.encode(s.name)+"&city="+Uri.encode(active.city)+"&view=map")));}catch(ActivityNotFoundException ex){toast("请安装地图应用或浏览器");}}}
    void share(){StringBuilder b=new StringBuilder(active.title+"\n"+active.city+" · "+active.start+" · "+active.days+"天\n");for(int i=0;i<active.days;i++){b.append("\n第 ").append(i+1).append(" 天\n");for(Trip.Stop s:active.onDay(i))b.append(s.time).append(" ").append(s.name).append(" · ").append(s.duration).append("分钟 · ").append(s.mode).append("\n").append(s.note.isEmpty()?"":s.note+"\n");}b.append("\n总预算 ¥").append(Trip.money(active.budget));Intent intent=new Intent(Intent.ACTION_SEND).setType("text/plain").putExtra(Intent.EXTRA_TEXT,b.toString());startActivity(Intent.createChooser(intent,"分享行程"));}
    void backupMenu(){new AlertDialog.Builder(this).setTitle("备份与恢复").setItems(new String[]{"导出全部旅行（JSON）","从备份导入（合并为新旅行）",getString(R.string.about_app)},(d,i)->{if(i==0){Intent in=new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("application/json").addCategory(Intent.CATEGORY_OPENABLE).putExtra(Intent.EXTRA_TITLE,getString(R.string.backup_prefix)+LocalDate.now()+".json");startActivityForResult(in,10);}if(i==1){Intent in=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(in,11);}if(i==2)new AlertDialog.Builder(this).setTitle(getString(R.string.app_name)+" 0.1.1").setMessage("个人旅行规划 · 离线版\n\n支持 Android 8.0 及以上。\n无需账号，不申请定位或网络权限。地图与分享由你选择的外部应用处理。\n\n没有实时票价、营业时间或自动路线计算。示例安排请自行核实。\n\n卸载会删除本地数据，请先导出备份。").setPositiveButton("知道了",null).show();}).show();}
    @Override public void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;try{if(req==10){if(loadFailed)throw new IOException();try(OutputStream out=getContentResolver().openOutputStream(data.getData(),"wt")){if(out==null)throw new IOException();out.write(TripStore.encode(trips).getBytes(StandardCharsets.UTF_8));}toast("备份已导出");}if(req==11){String raw;try(InputStream in=getContentResolver().openInputStream(data.getData());ByteArrayOutputStream buf=new ByteArrayOutputStream()){if(in==null)throw new IOException();byte[] block=new byte[8192];int n;while((n=in.read(block))!=-1){buf.write(block,0,n);if(buf.size()>5*1024*1024)throw new IllegalArgumentException("备份不能超过 5 MB");}raw=buf.toString("UTF-8");}ArrayList<Trip> imported=TripStore.decode(raw);if(imported.isEmpty())throw new IllegalArgumentException("备份中没有旅行");if(trips.size()+imported.size()>100)throw new IllegalArgumentException("合并后不能超过 100 个旅行");confirm("导入 "+imported.size()+" 个旅行？现有行程会保留。",()->{ArrayList<Trip> merged=new ArrayList<>(trips);for(Trip t:imported){t.id=UUID.randomUUID().toString();merged.add(t);}try{store.save(merged);trips=merged;loadFailed=false;active=imported.get(0);day=0;page=0;render();toast("已导入");}catch(Exception ex){toast("导入保存失败，原数据未修改");}});}}catch(Exception e){toast(e instanceof IllegalArgumentException?e.getMessage():"操作失败，请检查文件格式、存储空间或访问权限。");}}
    static final class Landscape extends View {
        final Paint p=new Paint(3);Landscape(Context c){super(c);setContentDescription("青绿色山峦与一轮暖阳的插画");}
        void fill(Canvas c,int color,float... points){p.setColor(color);Path path=new Path();path.moveTo(points[0],points[1]);for(int i=2;i<points.length;i+=2)path.lineTo(points[i],points[i+1]);path.close();c.drawPath(path,p);}
        @Override protected void onDraw(Canvas canvas){super.onDraw(canvas);canvas.save();canvas.scale(getWidth()/400f,getHeight()/160f);canvas.drawColor(0xffE7EDDF);p.setColor(0xffDCA76C);canvas.drawCircle(306,44,23,p);fill(canvas,0xffBDCCB4,0,138,72,42,126,101,202,33,328,151,400,117,400,160,0,160);fill(canvas,0xff729681,0,133,73,93,135,141,246,65,350,156,400,115,400,160,0,160);fill(canvas,0xff376D59,0,155,96,120,184,158,294,111,400,141,400,160,0,160);p.setColor(0xffF6F5F0);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(2);Path trail=new Path();trail.moveTo(213,160);trail.cubicTo(192,143,286,145,267,131);canvas.drawPath(trail,p);p.setStyle(Paint.Style.FILL);canvas.restore();}
    }
}
