package cn.lvxu.travel;
import android.content.Context;import android.net.Uri;import java.util.*;import java.util.regex.*;import java.io.*;import okhttp3.*;
/** Known map share URLs only. Never follows arbitrary redirects supplied in imported data. */
final class MapLinks {
 static String extract(String text)throws Exception {Matcher m=Pattern.compile("https://[^\\s<>\\\"，。]+",Pattern.CASE_INSENSITIVE).matcher(text);while(m.find()){String url=m.group();Uri u=Uri.parse(url);if(allowed(u))return url;}throw new IOException("请粘贴高德、腾讯或百度的 HTTPS 地图分享链接");}
 static boolean allowed(Uri u){String h=u.getHost();return "https".equalsIgnoreCase(u.getScheme())&&u.getUserInfo()==null&&(u.getPort()==-1||u.getPort()==443)&&h!=null&&(amap(h)||tencent(h)||baidu(h));}
 static boolean amap(String h){return h!=null&&(h.equals("amap.com")||h.endsWith(".amap.com")||h.equals("gaode.com")||h.endsWith(".gaode.com")||h.equals("guinness.autonavi.com"));}
 static boolean tencent(String h){return h!=null&&(h.equals("map.qq.com")||h.endsWith(".map.qq.com")||h.equals("apis.map.qq.com")||h.equals("3gimg.qq.com"));}
 static boolean baidu(String h){return h!=null&&(h.equals("map.baidu.com")||h.equals("api.map.baidu.com")||h.equals("j.map.baidu.com"));}
 static PlaceImporter.Place resolve(Context c,String text)throws Exception{String source=extract(text);if(amap(Uri.parse(source).getHost()))return PlaceImporter.resolve(text);String current=source;String html="";for(int n=0;n<4;n++){Uri uri=Uri.parse(current);if(!allowed(uri))throw new IOException("地图链接跳转到不受支持的网址");try(Response r=ApiHttp.CLIENT.newCall(new Request.Builder().url(current).build()).execute()){if(r.code()>=300&&r.code()<400){String location=r.header("Location");if(location==null)throw new IOException("地图分享链接不可用");HttpUrl next=r.request().url().resolve(location);if(next==null)throw new IOException("无效跳转");current=next.toString();continue;}if(!r.isSuccessful())throw new IOException("地图分享暂不可用（HTTP "+r.code()+"）");if(r.body()!=null){try(InputStream in=r.body().byteStream()){ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] b=new byte[4096];int size;while((size=in.read(b))!=-1){if(out.size()+size>512*1024)break;out.write(b,0,size);}html=out.toString("UTF-8");}}break;}}
  Uri u=Uri.parse(current);PlaceImporter.Place p=parse(u);p.sourceUrl=current;if(p.name.isEmpty()){Matcher title=Pattern.compile("<title[^>]*>([^<]{1,150})</title>",Pattern.CASE_INSENSITIVE).matcher(html);if(title.find())p.name=title.group(1).replaceAll("[-_].*(腾讯|百度).*","").trim();}if(p.name.isEmpty())throw new IOException("链接未提供可识别地点，请使用地图搜索或手动添加");return p;}
 static PlaceImporter.Place parse(Uri u){PlaceImporter.Place p=new PlaceImporter.Place();p.sourceUrl=u.toString();p.coordinateSystem=baidu(u.getHost())?"BD09":"GCJ02";p.name=first(u,"title","name","poiname","keyword");p.address=first(u,"content","address","addr");String coord=first(u,"location","coord","center");String marker=u.getQueryParameter("marker");if(marker!=null){Matcher m=Pattern.compile("coord:([-0-9.]+),([-0-9.]+)").matcher(marker);if(m.find())coord=m.group(1)+","+m.group(2);m=Pattern.compile("title:([^;]+)").matcher(marker);if(m.find())p.name=m.group(1);m=Pattern.compile("addr:([^;]+)").matcher(marker);if(m.find())p.address=m.group(1);}if(coord.isEmpty()){String lat=first(u,"lat","latitude"),lon=first(u,"lng","lon","longitude");coord=lat+","+lon;}try{String[] parts=coord.split(",");double lat=Double.parseDouble(parts[0]),lon=Double.parseDouble(parts[1]);if(Double.isFinite(lat)&&Double.isFinite(lon)&&Math.abs(lat)<=90&&Math.abs(lon)<=180){p.lat=lat;p.lon=lon;}}catch(Exception ignored){}String type=u.getQueryParameter("coord_type");if("gcj02".equalsIgnoreCase(type))p.coordinateSystem="GCJ02";if("wgs84".equalsIgnoreCase(type))p.coordinateSystem="WGS84";p.name=PlaceImporter.clip(p.name,120);p.address=PlaceImporter.clip(p.address,300);return p;}
 static String first(Uri u,String... keys){for(String k:keys){String s=u.getQueryParameter(k);if(s!=null&&!s.trim().isEmpty())return s.trim();}return "";}
}
