package cn.lvxu.travel;
import android.content.Context;import okhttp3.*;import org.json.*;import java.util.*;import java.io.IOException;
/** REST route capability shared by map screens and planning tools. */
final class MapRoutes {
 interface Adapter {HttpUrl url(String key,double[] from,double[] to,String mode);JSONObject result(JSONObject response)throws Exception;}
 static Adapter adapter(String id){if("tencent".equals(id))return new Adapter(){public HttpUrl url(String k,double[] f,double[] t,String mode){return ApiHttp.url("https://apis.map.qq.com/ws/direction/v1/"+mode+"/").newBuilder().addQueryParameter("key",k).addQueryParameter("from",latlon(f)).addQueryParameter("to",latlon(t)).build();}public JSONObject result(JSONObject o)throws Exception{MapService.status(o,false);return first(o.getJSONObject("result").optJSONArray("routes"));}};if("baidu".equals(id))return new Adapter(){public HttpUrl url(String k,double[] f,double[] t,String mode){return ApiHttp.url("https://api.map.baidu.com/directionlite/v1/"+mode).newBuilder().addQueryParameter("ak",k).addQueryParameter("origin",latlon(f)).addQueryParameter("destination",latlon(t)).addQueryParameter("coord_type","gcj02").build();}public JSONObject result(JSONObject o)throws Exception{MapService.status(o,false);return first(o.getJSONObject("result").optJSONArray("routes"));}};return new Adapter(){public HttpUrl url(String k,double[] f,double[] t,String mode){return ApiHttp.url("https://restapi.amap.com/v3/direction/"+mode).newBuilder().addQueryParameter("key",k).addQueryParameter("origin",lonlat(f)).addQueryParameter("destination",lonlat(t)).build();}public JSONObject result(JSONObject o)throws Exception{MapService.status(o,true);return first(o.getJSONObject("route").optJSONArray("paths"));}};}
 static String estimate(Context c,Trip.Stop from,Trip.Stop to,boolean walking)throws Exception{ApiConfig config=new ApiConfig(c);String id=config.mapProvider(),key=config.mapKey(id);if(key.isEmpty())throw new IOException("请先在高级设置中配置地图 API Key");Adapter a=adapter(id);JSONObject route=a.result(ApiHttp.json(new Request.Builder().url(a.url(key,MapService.gcj(from),MapService.gcj(to),walking?"walking":"driving")).build()));double meters=route.optDouble("distance",-1),duration=route.optDouble("duration",-1);if(meters<0||duration<0)throw new IOException("暂无可用路线，请在地图应用中查看");if("tencent".equals(id))duration*=60;return MapService.name(id)+" · "+(walking?"步行":"驾车")+"约 "+GeoMath.distance(meters)+" / "+Math.max(1,Math.round(duration/60))+" 分钟（仅供参考）";}
 static JSONObject first(JSONArray a)throws Exception{if(a==null||a.length()==0)throw new IOException("未找到可用路线");return a.getJSONObject(0);}
 static String latlon(double[] p){return String.format(Locale.ROOT,"%.6f,%.6f",p[0],p[1]);}static String lonlat(double[] p){return String.format(Locale.ROOT,"%.6f,%.6f",p[1],p[0]);}
}
