package cn.lvxu.travel;
import android.app.*;import android.text.*;import android.widget.*;import java.time.*;import java.util.*;
final class SearchUi {
 private final MainActivity a;private final SearchIndex.Query query=new SearchIndex.Query();private final LinkedHashMap<String,SearchIndex.Result> selected=new LinkedHashMap<>();private LinearLayout results;private PageUi page;private int limit=50;
 SearchUi(MainActivity a){this.a=a;}
 void show(){page=new PageUi(a,"搜索与筛选");EditText keyword=a.field(page.body,"搜索旅行、地点、预算、备注、清单或打卡","",1);a.pair(page.body,a.action("筛选条件",false,this::filters),a.action("清除筛选",false,()->{query.tagId="";query.type="全部";query.from=query.to=null;query.after=query.before=null;query.minCost=query.maxCost=null;keyword.setText("");query.text="";selected.clear();refresh();}));a.pair(page.body,a.action("刷新结果",false,this::refresh),a.action("删除所选",false,this::deleteSelected));results=a.col();page.body.addView(results);keyword.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int af){}public void onTextChanged(CharSequence s,int st,int b,int c){query.text=s.toString();limit=50;selected.clear();refresh();}public void afterTextChanged(Editable e){}});page.surface.getViewTreeObserver().addOnWindowFocusChangeListener(has->{if(has)refresh();});page.show();refresh();}
 private void filters(){LinearLayout f=a.col();Spinner type=a.select(f,"搜索范围",new String[]{"全部","旅行","行程","地点","预算","备注","清单","打卡"},query.type);ArrayList<TagRepository.Tag> tags=new ArrayList<>(new TagRepository(a).all());String[] labels=new String[tags.size()+1];labels[0]="全部标签";int old=0;for(int i=0;i<tags.size();i++){labels[i+1]=tags.get(i).name;if(tags.get(i).id.equals(query.tagId))old=i+1;}Spinner tag=a.select(f,"标签",labels,labels[old]);EditText from=a.field(f,"起始日期（YYYY-MM-DD，选填）",str(query.from),1),to=a.field(f,"结束日期（选填）",str(query.to),1),after=a.field(f,"每日开始时间（HH:mm，选填）",str(query.after),1),before=a.field(f,"每日结束时间（选填）",str(query.before),1),min=a.field(f,"最低花费 / 预算（元，选填）",query.minCost==null?"":Trip.money(query.minCost),8194),max=a.field(f,"最高花费 / 预算（元，选填）",query.maxCost==null?"":Trip.money(query.maxCost),8194);a.dialog("组合筛选",f,()->{try{LocalDate lo=date(from),hi=date(to);LocalTime l=time(after),h=time(before);Long low=money(min),high=money(max);if(lo!=null&&hi!=null&&lo.isAfter(hi)||l!=null&&h!=null&&l.isAfter(h)||low!=null&&high!=null&&low>high)throw new IllegalArgumentException();query.from=lo;query.to=hi;query.after=l;query.before=h;query.minCost=low;query.maxCost=high;query.type=type.getSelectedItem().toString();query.tagId=tag.getSelectedItemPosition()==0?"":tags.get(tag.getSelectedItemPosition()-1).id;selected.clear();refresh();}catch(Exception e){throw new IllegalArgumentException("请检查日期、时间和金额范围，起始值不能大于结束值");}},null);}
 private void refresh(){if(results==null)return;results.removeAllViews();List<SearchIndex.Result> found=SearchIndex.search(a.trips,query);results.addView(a.text(found.size()+" 条结果",13,MainActivity.MUTED));if(found.isEmpty()){results.addView(a.text("没有符合条件的内容。",14,MainActivity.MUTED));return;}String group="";int shown=0;for(SearchIndex.Result r:found){if(shown++>=limit)break;if(!group.equals(r.type)){group=r.type;results.addView(a.bold(group,17,MainActivity.INK));}LinearLayout c=a.card(results);CheckBox box=new CheckBox(a);box.setText(r.title);box.setTextColor(MainActivity.INK);box.setChecked(selected.containsKey(r.key()));box.setOnCheckedChangeListener((v,on)->{if(on)selected.put(r.key(),r);else selected.remove(r.key());});c.addView(box);c.addView(a.text(r.detail,13,MainActivity.MUTED));a.pair(c,a.action("打开 / 修改",false,()->a.openSearchResult(r)),a.action("删除",false,()->a.confirm("删除这条"+r.type+"记录？",()->{remove(r);a.changed();selected.remove(r.key());refresh();})));}if(found.size()>limit)results.addView(a.action("加载更多结果",false,()->{limit+=50;refresh();}));}
 private void deleteSelected(){if(selected.isEmpty()){a.toast("请先选择要删除的内容");return;}ArrayList<SearchIndex.Result> batch=new ArrayList<>(selected.values());a.confirm("删除所选的 "+batch.size()+" 条记录？此操作不可撤销。",()->{for(SearchIndex.Result r:batch)remove(r);selected.clear();a.changed();refresh();});}
 private void remove(SearchIndex.Result r){for(Trip t:new ArrayList<>(a.trips))if(t.id.equals(r.tripId)){if("旅行".equals(r.type)){a.trips.remove(t);if(a.active==t)a.active=a.trips.isEmpty()?null:a.trips.get(0);}else if("地点".equals(r.type))t.stops.removeIf(s->s.id.equals(r.itemId));else if("预算".equals(r.type))t.expenses.removeIf(s->s.id.equals(r.itemId));else if("清单".equals(r.type))t.items.removeIf(s->s.id.equals(r.itemId));else if("打卡".equals(r.type))t.checkins.removeIf(s->s.id.equals(r.itemId));}}
 private static String str(Object o){return o==null?"":o.toString();}private static String value(EditText e){return e.getText().toString().trim();}private static LocalDate date(EditText e){return value(e).isEmpty()?null:LocalDate.parse(value(e));}private static LocalTime time(EditText e){return value(e).isEmpty()?null:LocalTime.parse(value(e));}private static Long money(EditText e){return value(e).isEmpty()?null:Trip.cents(value(e));}
}
