package cn.lvxu.travel;

import android.app.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.drawable.ColorDrawable;
import android.net.Uri;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.time.LocalDate;
import java.util.*;

/** Right-side settings drawer and callbacks. One instance should be retained by MainActivity. */
public final class SettingsUi {
    public static final int EXPORT_ZIP=330,IMPORT_ZIP=331;
    private final MainActivity a;private final AppPrefs prefs;private final WebDavService dav;private final UpdateService updates;
    public SettingsUi(MainActivity a){this.a=a;this.prefs=a.prefs;this.dav=new WebDavService(a);this.updates=new UpdateService(a,prefs);}
    public void open(){Dialog d=new Dialog(a);ScrollView scroll=new ScrollView(a);scroll.setBackgroundColor(MainActivity.SURFACE);LinearLayout box=a.col();box.setPadding(a.dp(22),a.dp(18),a.dp(22),a.dp(30));scroll.addView(box);LinearLayout bar=a.row();TextView back=a.bold("‹",38,MainActivity.INK);back.setGravity(Gravity.CENTER);back.setContentDescription("返回");back.setFocusable(true);back.setOnClickListener(v->d.dismiss());bar.addView(back,new LinearLayout.LayoutParams(a.dp(48),a.dp(52)));TextView spacer=a.text("",1,MainActivity.INK);bar.addView(spacer,new LinearLayout.LayoutParams(0,1,1));TextView title=a.bold("设置",25,MainActivity.INK);title.setGravity(Gravity.CENTER_VERTICAL|Gravity.RIGHT);bar.addView(title,new LinearLayout.LayoutParams(-2,a.dp(52)));box.addView(bar);a.space(box,8);profile(box,d);webdav(box,d);personalize(box,d);backup(box);activation(box);version(box);d.setContentView(scroll);Window w=d.getWindow();if(w!=null){w.setBackgroundDrawable(new ColorDrawable(MainActivity.SURFACE));w.setGravity(Gravity.RIGHT);w.setLayout((int)(a.getResources().getDisplayMetrics().widthPixels*.90f),-1);w.setDimAmount(.28f);w.addFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND);w.getAttributes().windowAnimations=android.R.style.Animation_Dialog;}d.setOnShowListener(x->{Window q=d.getWindow();if(q!=null)q.setLayout((int)(a.getResources().getDisplayMetrics().widthPixels*.90f),-1);scroll.setTranslationX(scroll.getWidth());scroll.animate().translationX(0).setDuration(220).start();});d.show();}
    private void profile(LinearLayout box,Dialog drawer){section(box,"个人资料");LinearLayout c=a.card(box);LinearLayout head=a.row();ImageView avatar=new ImageView(a);avatar.setScaleType(ImageView.ScaleType.CENTER_CROP);avatar.setBackgroundColor(MainActivity.PALE);File avatarFile=a.mediaFile(prefs.avatar());if(avatarFile!=null&&avatarFile.isFile())avatar.setImageURI(Uri.fromFile(avatarFile));else avatar.setImageResource(cn.lvxu.travel.R.drawable.avatar_wheat);avatar.setContentDescription("更换头像");avatar.setFocusable(true);avatar.setOnClickListener(v->a.pickImage(path->{prefs.setAvatar(path);drawer.dismiss();a.render();open();}));head.addView(avatar,new LinearLayout.LayoutParams(a.dp(64),a.dp(64)));View gap=new View(a);head.addView(gap,new LinearLayout.LayoutParams(a.dp(12),1));LinearLayout labels=a.col();TextView nickname=a.bold(prefs.nickname().isEmpty()?"旅行者":prefs.nickname(),19,MainActivity.INK);nickname.setContentDescription("修改昵称");nickname.setFocusable(true);nickname.setOnClickListener(v->editNickname(drawer));labels.addView(nickname);String expiry=prefs.activationExpires();labels.addView(a.text(prefs.paid()?"已激活 · "+prefs.activationSubject()+(expiry.isEmpty()?"":" · 至 "+expiry):"本地资料 · 未激活",13,MainActivity.MUTED));head.addView(labels,new LinearLayout.LayoutParams(0,-2,1));c.addView(head);a.space(c,12);a.pair(c,a.action("编辑昵称",false,()->editNickname(drawer)),a.action("更换头像",false,()->a.pickImage(path->{prefs.setAvatar(path);drawer.dismiss();a.render();open();})));}
    private void editNickname(Dialog drawer){LinearLayout f=a.col();EditText n=a.field(f,"昵称",prefs.nickname(),InputType.TYPE_CLASS_TEXT);a.dialog("个人资料",f,()->{prefs.setNickname(a.required(n,40));drawer.dismiss();a.render();open();},null);}
    private void personalize(LinearLayout box,Dialog drawer){section(box,"个性化");LinearLayout c=a.card(box);Spinner theme=a.select(c,"主题",new String[]{"浅色","深色","跟随系统"},themeLabel());theme.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){boolean first=true;public void onNothingSelected(android.widget.AdapterView<?> p){}public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){if(first){first=false;return;}prefs.setTheme(pos==1?"dark":pos==2?"system":"light");drawer.dismiss();a.render();open();}});Spinner home=a.select(c,"默认首页",new String[]{"旅行","行程","预算","清单","打卡"},homeLabel());home.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){boolean first=true;public void onNothingSelected(android.widget.AdapterView<?> p){}public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){if(first){first=false;return;}prefs.setDefaultHome(new String[]{"home","itinerary","budget","checklist","checkin"}[pos]);a.toast("默认首页已保存");}});c.addView(a.action("选择首页背景",false,()->{drawer.dismiss();a.media.showBackgroundPicker();}));a.space(c,12);c.addView(a.text("长按并拖动下面的项目来调整底栏顺序。至少保留一个入口。",12,MainActivity.MUTED));a.space(c,8);navEditor(c);}
    private String homeLabel(){String h=prefs.defaultHome();if("itinerary".equals(h))return "行程";if("budget".equals(h))return "预算";if("checklist".equals(h))return "清单";if("checkin".equals(h))return "打卡";return "旅行";}
    private String themeLabel(){return "dark".equals(prefs.theme())?"深色":"system".equals(prefs.theme())?"跟随系统":"浅色";}
    private void navEditor(LinearLayout parent){LinearLayout list=a.col();parent.addView(list);renderNavRows(list);list.setOnDragListener((v,e)->{if(e.getAction()==DragEvent.ACTION_DROP){String id=String.valueOf(e.getLocalState());int target=0;for(int i=0;i<list.getChildCount();i++)if(e.getY()>list.getChildAt(i).getBottom())target=i+1;ArrayList<String> order=new ArrayList<>(prefs.navOrder());order.remove(id);order.add(Math.min(target,order.size()),id);prefs.setNavOrder(order);renderNavRows(list);a.render();return true;}return e.getAction()==DragEvent.ACTION_DRAG_STARTED||e.getAction()==DragEvent.ACTION_DRAG_ENTERED||e.getAction()==DragEvent.ACTION_DRAG_LOCATION||e.getAction()==DragEvent.ACTION_DRAG_EXITED||e.getAction()==DragEvent.ACTION_DRAG_ENDED;});}
    private void renderNavRows(LinearLayout list){list.removeAllViews();for(String id:prefs.navOrder()){LinearLayout row=a.row();row.setPadding(a.dp(8),a.dp(7),a.dp(4),a.dp(7));TextView handle=a.bold("☰  "+navName(id),15,MainActivity.INK);row.addView(handle,new LinearLayout.LayoutParams(0,-2,1));Switch visible=new Switch(a);visible.setChecked(prefs.navVisible(id));visible.setContentDescription("显示"+navName(id));visible.setOnCheckedChangeListener((b,on)->{if(!on&&visibleCount()<=1){b.setChecked(true);a.toast("底栏至少保留一个入口");return;}prefs.setNavVisible(id,on);a.render();});row.addView(visible);View.OnLongClickListener drag=v->{v.startDragAndDrop(null,new View.DragShadowBuilder(row),id,0);return true;};row.setOnLongClickListener(drag);handle.setOnLongClickListener(drag);list.addView(row);}}
    private int visibleCount(){int n=0;for(String x:prefs.navOrder())if(prefs.navVisible(x))n++;return n;}
    private String navName(String id){if("home".equals(id))return "旅行";if("itinerary".equals(id))return "行程";if("budget".equals(id))return "预算";if("checklist".equals(id))return "清单";return "足迹";}
    private void backup(LinearLayout box){section(box,"备份与恢复");LinearLayout c=a.card(box);c.addView(a.text("ZIP 备份包含全部旅行、照片与非敏感偏好。恢复会先校验完整性，再保留现有旅行并导入。",13,MainActivity.MUTED));a.space(c,12);a.pair(c,a.action("导出完整备份",true,()->{Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("application/zip").addCategory(Intent.CATEGORY_OPENABLE).putExtra(Intent.EXTRA_TITLE,"麦穗旅序-"+LocalDate.now()+".zip");a.startActivityForResult(i,EXPORT_ZIP);}),a.action("从 ZIP 恢复",false,()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("application/zip").addCategory(Intent.CATEGORY_OPENABLE);a.startActivityForResult(i,IMPORT_ZIP);}));}
    private void webdav(LinearLayout box,Dialog drawer){section(box,"WebDAV 云备份");LinearLayout c=a.card(box);c.addView(a.text(dav.configured()?"已配置："+dav.endpoint():"仅支持 HTTPS。账号与密码由系统安全密钥加密保存在本机。",12,MainActivity.MUTED));a.space(c,10);c.addView(a.action("配置并测试",false,()->configureDav(drawer)));a.space(c,8);if(dav.configured()){a.pair(c,a.action("立即上传",true,this::davUpload),a.action("选择云端备份恢复",false,this::davRestore));}}
    private void configureDav(Dialog drawer){LinearLayout f=a.col();EditText url=a.field(f,"HTTPS WebDAV 文件夹地址",dav.endpoint(),InputType.TYPE_TEXT_VARIATION_URI);EditText user=a.field(f,"用户名","",InputType.TYPE_CLASS_TEXT);EditText pass=a.field(f,"密码","",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);a.dialog("WebDAV",f,()->{String u=a.required(url,1000),name=user.getText().toString(),secret=pass.getText().toString();a.runJob("正在连接 WebDAV",()->{dav.configureAndTest(u,name,secret);return "连接成功";},()->{drawer.dismiss();a.toast("WebDAV 连接成功");open();});},dav.configured()?()->{dav.clear();drawer.dismiss();a.toast("已清除 WebDAV 配置");open();}:null);}
    private void davUpload(){a.runJob("正在上传备份",()->{File tmp=File.createTempFile("dav-backup-",".zip",a.getCacheDir());try{try(OutputStream out=new FileOutputStream(tmp)){BackupArchive.write(a,a.trips,prefs,out);}String name="maisui-"+LocalDate.now()+"-"+System.currentTimeMillis()+".zip";try(InputStream in=new FileInputStream(tmp)){dav.upload(name,in,tmp.length());}return name;}finally{tmp.delete();}},()->a.toast("云备份上传完成"));}
    private void davRestore(){final List<String>[] names=new List[]{Collections.emptyList()};a.runJob("正在读取云端备份",()->{names[0]=dav.list();return ""+names[0].size();},()->{if(names[0].isEmpty()){a.toast("云端没有 ZIP 备份");return;}String[] values=names[0].toArray(new String[0]);new AlertDialog.Builder(a).setTitle("选择要恢复的备份").setItems(values,(d,i)->a.confirm("恢复 "+values[i]+"？",()->downloadRestore(values[i]))).show();});}
    private void downloadRestore(String name){a.runJob("正在下载并恢复",()->{File tmp=File.createTempFile("dav-restore-",".zip",a.getCacheDir());try{try(OutputStream out=new FileOutputStream(tmp)){dav.download(name,out);}try(InputStream in=new FileInputStream(tmp)){return String.valueOf(BackupArchive.restore(a,in,a.store,a.trips,prefs));}}finally{tmp.delete();}},()->reloadAfterRestore());}
    private void activation(LinearLayout box){section(box,"激活");LinearLayout c=a.card(box);if(prefs.paid()){c.addView(a.bold("已激活",18,MainActivity.GREEN));String expiry=prefs.activationExpires();c.addView(a.text(prefs.activationSubject()+(expiry.isEmpty()?"":" · 有效期至 "+expiry),12,MainActivity.MUTED));return;}c.addView(a.text("激活码可离线验证开发者签名，不需要账号或联网。",13,MainActivity.MUTED));a.space(c,10);c.addView(a.action("输入激活码",true,()->{LinearLayout f=a.col();EditText code=a.field(f,"激活码","",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS);a.dialog("离线激活",f,()->{try{String who=new ActivationService(prefs).activate(a.required(code,12000));a.toast("已为 "+who+" 激活");open();}catch(Exception e){throw new IllegalArgumentException(e.getMessage()==null?"激活失败":e.getMessage());}},null);}));}
    private void version(LinearLayout box){section(box,"关于");LinearLayout c=a.card(box);String found="";try{found=a.getPackageManager().getPackageInfo(a.getPackageName(),0).versionName;}catch(Exception ignored){}final String version=found;TextView v=a.action("麦穗旅序 "+version+"  ·  检查更新",false,()->checkUpdate(true));c.addView(v);a.space(c,8);c.addView(a.action("设置可信更新镜像",false,()->{LinearLayout f=a.col();EditText url=a.field(f,"GitHub API 或可信 HTTPS 镜像",prefs.updateMirror(),InputType.TYPE_TEXT_VARIATION_URI);a.dialog("更新来源",f,()->{String value=a.required(url,1000);if(!value.startsWith("https://"))throw new IllegalArgumentException("更新镜像必须使用 HTTPS");prefs.setUpdateMirror(value);a.toast("更新来源已保存");},null);}));a.space(c,8);c.addView(a.action("重新查看使用引导",false,()->{prefs.setTutorialDone(false);a.showTutorial();}));}
    public void checkDailyUpdate(){String today=LocalDate.now().toString();if(today.equals(prefs.lastUpdateDay()))return;prefs.setLastUpdateDay(today);new Thread(()->{try{UpdateService.Release r=updates.check();if(r.state==UpdateService.State.AVAILABLE)a.runOnUiThread(()->{if(!a.isFinishing())new AlertDialog.Builder(a).setTitle("发现新版本 "+r.versionName).setMessage(r.notes).setNegativeButton("稍后",null).setPositiveButton("下载",(d,w)->downloadUpdate(r)).show();});}catch(Exception ignored){}},"daily-update-check").start();}
    private void checkUpdate(boolean manual){final UpdateService.Release[] found=new UpdateService.Release[1];a.runJob("正在检查更新",()->{found[0]=updates.check();return found[0].state.name();},()->{UpdateService.Release r=found[0];if(r.state==UpdateService.State.AVAILABLE)new AlertDialog.Builder(a).setTitle("发现新版本 "+r.versionName).setMessage(r.notes).setNegativeButton("稍后",null).setPositiveButton("下载",(d,w)->downloadUpdate(r)).show();else if(manual)a.toast(r.state==UpdateService.State.UP_TO_DATE?"已经是最新版本":r.notes);});}
    private void downloadUpdate(UpdateService.Release r){final File[] apk=new File[1];a.runJob("正在下载并验证更新",()->{apk[0]=updates.downloadAndVerify(r);return apk[0].getName();},()->updates.requestInstall(apk[0]));}
    public boolean onActivityResult(int req,int result,Intent data){if(req!=EXPORT_ZIP&&req!=IMPORT_ZIP)return false;if(result!=Activity.RESULT_OK||data==null||data.getData()==null)return true;Uri uri=data.getData();if(req==EXPORT_ZIP)a.runJob("正在导出完整备份",()->{try(OutputStream out=a.getContentResolver().openOutputStream(uri,"wt")){if(out==null)throw new IOException("无法写入所选文件");BackupArchive.write(a,a.trips,prefs,out);}return "ok";},()->a.toast("完整备份已导出"));else a.confirm("恢复备份并保留现有旅行？",()->a.runJob("正在校验并恢复",()->{try(InputStream in=a.getContentResolver().openInputStream(uri)){if(in==null)throw new IOException("无法读取所选文件");return String.valueOf(BackupArchive.restore(a,in,a.store,a.trips,prefs));}},this::reloadAfterRestore));return true;}
    private void section(LinearLayout box,String title){a.space(box,16);box.addView(a.bold(title,18,MainActivity.INK));a.space(box,10);}
    private void reloadAfterRestore(){try{a.trips=a.store.read();a.active=a.trips.isEmpty()?null:a.trips.get(0);a.loadFailed=false;a.page=0;a.render();a.toast("备份已恢复");}catch(Exception e){a.toast("恢复已保存，但重新读取失败，请重启应用");}}
}
