package cn.lvxu.travel;

import android.content.*;import org.json.*;import java.util.*;

/** Persistent tag and group registry. Trips keep their own label snapshots for export. */
final class TagRepository {
 static final String PREF="tag-registry-v1",KEY="tags",REGISTRY="registry-v2";private final SharedPreferences prefs;
 static final class Tag {String id,name;int color;boolean system;final ArrayList<String> groupIds=new ArrayList<>();Tag(String i,String n,int c,boolean s){id=i;name=n;color=c;system=s;}}
 static final class Group {String id,name,description;boolean system;Group(String i,String n,String d,boolean s){id=i;name=n;description=d;system=s;}}
 static final int DEFAULT_COLOR=0xff829399,MAX_TAGS=200,MAX_GROUPS=50;
 TagRepository(Context c){prefs=c.getApplicationContext().getSharedPreferences(PREF,Context.MODE_PRIVATE);}
 List<Tag> all(){return state().tags;} List<Group> groups(){return state().groups;}
 Tag find(String id){for(Tag t:all())if(t.id.equals(id))return t;return null;} Group group(String id){for(Group g:groups())if(g.id.equals(id))return g;return null;}
 List<Tag> inGroup(String id){ArrayList<Tag> out=new ArrayList<>();for(Tag t:all())if(id==null||id.isEmpty()||t.groupIds.contains(id))out.add(t);return out;}
 String description(Tag t){String[] names={"自然风光","人文历史","城市漫游","古迹遗址","建筑设计","艺术文化","公园园林","海滨水景","山野秘境","美食探索","咖啡小憩","购物逛街","娱乐体验","休闲度假","夜景夜游","摄影打卡","小众探索","民俗体验","宗教文化","亲子游玩","户外运动","观景胜地","季节限定","特色地标"};String[] notes={"山海湖瀑与自然景观","历史脉络与文化体验","街巷散步和城市日常","遗址古城与历史现场","特色建筑和设计空间","展览演出与文化场所","园林绿地和慢游空间","海岸湖畔与水上活动","徒步探秘和野外风光","当地味道和餐厅寻访","咖啡馆与午后休憩","商圈市集和伴手礼","游乐演出和趣味项目","酒店度假和放松时光","夜色灯光和晚间路线","取景地与拍摄行程","冷门路线和隐藏去处","节庆习俗和在地生活","寺庙教堂与信仰空间","适合儿童的游玩安排","徒步骑行和运动体验","登高远眺和经典视角","花期节日和限定风光","地标建筑和城市名片"};for(int i=0;i<names.length;i++)if(names[i].equals(t.name))return notes[i];return "旅行分类标签";}
 Tag create(String name,int color){return create(name,color,Collections.<String>emptyList());}
 Tag create(String name,int color,Collection<String> groupIds){State s=state();if(s.tags.size()>=MAX_TAGS)throw new IllegalArgumentException("最多 200 个标签");name=clean(name);unique(s.tags,null,name);Tag t=new Tag(Trip.uid(),name,color,false);setGroups(s,t,groupIds);s.tags.add(t);write(s);return t;}
 void rename(String id,String name,int color){rename(id,name,color,null);}
 void rename(String id,String name,int color,List<Trip> trips){State s=state();Tag t=need(s,id);name=clean(name);unique(s.tags,id,name);t.name=name;t.color=color;write(s);if(trips!=null)replaceEmbedded(trips,id,name);}
 void delete(String id,List<Trip> trips){State s=state();Tag removed=need(s,id);s.deletedSystemIds.add(id);for(Iterator<Tag> it=s.tags.iterator();it.hasNext();)if(it.next().id.equals(id))it.remove();write(s);if(trips!=null)for(Trip t:trips){detach(t.tagIds,t.tagNames,id);for(Trip.Stop stop:t.stops)detach(stop.tagIds,stop.tagNames,id);}}
 Group createGroup(String name,String description){State s=state();if(s.groups.size()>=MAX_GROUPS)throw new IllegalArgumentException("最多 50 个标签组");name=clean(name);uniqueGroups(s.groups,null,name);Group g=new Group(Trip.uid(),name,Trip.bounded(description==null?"":description.trim(),120),false);s.groups.add(g);write(s);return g;}
 void editGroup(String id,String name,String description,Collection<String> tagIds){State s=state();Group g=needGroup(s,id);name=clean(name);uniqueGroups(s.groups,id,name);g.name=name;g.description=Trip.bounded(description==null?"":description.trim(),120);for(Tag t:s.tags)t.groupIds.remove(id);for(String tagId:tagIds){Tag t=find(s.tags,tagId);if(t!=null&&!t.groupIds.contains(id))t.groupIds.add(id);}write(s);}
 /** Removing a group only removes its memberships; labels remain available elsewhere. */
 void deleteGroup(String id){State s=state();needGroup(s,id);for(Iterator<Group> it=s.groups.iterator();it.hasNext();)if(it.next().id.equals(id))it.remove();for(Tag t:s.tags)t.groupIds.remove(id);write(s);}
 void mergeEmbedded(Trip trip){State s=state();Map<String,String> mapping=new LinkedHashMap<>();ArrayList<Map<String,String>> labels=new ArrayList<>();labels.add(trip.tagNames);for(Trip.Stop stop:trip.stops)labels.add(stop.tagNames);boolean changed=false;for(Map<String,String> names:labels)for(Map.Entry<String,String> e:names.entrySet()){String id=e.getKey(),name=e.getValue();if(s.deletedSystemIds.contains(id)){mapping.put(id,"");continue;}Tag existing=find(s.tags,id);if(existing==null)existing=findByName(s.tags,name);if(existing!=null)mapping.put(id,existing.id);else changed|=merge(s,id,name);}if(changed)write(s);remap(trip,mapping);}
 private static boolean merge(State s,String id,String name){if(id==null||id.length()>100||name==null||name.trim().isEmpty()||s.deletedSystemIds.contains(id)||find(s.tags,id)!=null)return false;if(s.tags.size()>=MAX_TAGS||findByName(s.tags,name)!=null)return false;s.tags.add(new Tag(id,clean(name),DEFAULT_COLOR,false));return true;}
 /** Snapshot used by portable backups; it deliberately excludes any unrelated preferences or secrets. */
 JSONObject exportJson(){try{return encode(state());}catch(Exception e){throw new IllegalStateException("标签备份失败");}}
 /**
  * Merges custom registry entries from a backup. Missing system IDs are intentionally not restored:
  * a local deletion of a preset remains a deletion. The result maps incoming tag IDs to local IDs.
  */
 static void validateSnapshot(JSONObject snapshot){try{read(snapshot);}catch(JSONException e){throw new IllegalArgumentException("标签备份内容无效");}}
 static final class MergePlan {final JSONObject snapshot;final Map<String,String> ids;MergePlan(JSONObject s,Map<String,String> i){snapshot=s;ids=i;}}
 MergePlan prepareImport(JSONObject incoming){try{State add=read(incoming),local=state();Map<String,String> gm=new LinkedHashMap<>(),tm=new LinkedHashMap<>();
  for(Group g:add.groups){Group old=groupIn(local,g.id);Group byName=findGroupByName(local.groups,g.name);if(old!=null&&(byName==null||byName==old)){old.name=g.name;old.description=g.description;}else if(byName!=null)old=byName;if(old==null){if(local.groups.size()>=MAX_GROUPS)throw new IllegalArgumentException("合并后标签组超过 50 个");old=new Group(g.id,g.name,g.description,g.system);local.groups.add(old);}gm.put(g.id,old.id);}
  for(Tag t:add.tags){if(local.deletedSystemIds.contains(t.id)){tm.put(t.id,"");continue;}Tag old=find(local.tags,t.id);Tag byName=findByName(local.tags,t.name);if(old!=null&&(byName==null||byName==old)){old.name=t.name;old.color=t.color;}else if(byName!=null)old=byName;if(old==null){if(local.tags.size()>=MAX_TAGS)throw new IllegalArgumentException("合并后标签超过 200 个");old=new Tag(t.id,t.name,t.color,t.system);local.tags.add(old);}for(String gid:t.groupIds){String mapped=gm.get(gid);if(mapped!=null&&!old.groupIds.contains(mapped))old.groupIds.add(mapped);}tm.put(t.id,old.id);}
  return new MergePlan(encode(local),tm);
 }catch(IllegalArgumentException e){throw e;}catch(Exception e){throw new IllegalArgumentException("标签备份内容无效");}}
 void commitImport(MergePlan plan){try{write(read(plan.snapshot));}catch(JSONException e){throw new IllegalArgumentException("标签备份内容无效");}}
 Map<String,String> importJson(JSONObject incoming){MergePlan plan=prepareImport(incoming);commitImport(plan);return plan.ids;}
 void remap(Trip trip,Map<String,String> mapping){remapLabels(trip.tagIds,trip.tagNames,mapping);for(Trip.Stop stop:trip.stops)remapLabels(stop.tagIds,stop.tagNames,mapping);}
 private void remapLabels(ArrayList<String> ids,LinkedHashMap<String,String> names,Map<String,String> mapping){ArrayList<String> result=new ArrayList<>();LinkedHashMap<String,String> labels=new LinkedHashMap<>();for(String id:ids){String mapped=mapping.containsKey(id)?mapping.get(id):id;if(mapped==null||mapped.isEmpty())continue;Tag tag=find(mapped);if(!result.contains(mapped))result.add(mapped);labels.put(mapped,tag==null?names.get(id):tag.name);}ids.clear();ids.addAll(result);names.clear();names.putAll(labels);}
 static void assign(ArrayList<String> ids,LinkedHashMap<String,String> names,Collection<Tag> selected){ids.clear();names.clear();for(Tag t:selected){ids.add(t.id);names.put(t.id,t.name);}}
 /** Replaces only selections visible in a group, preserving selections from other groups. */
 static void assignGroup(ArrayList<String> ids,LinkedHashMap<String,String> names,Collection<Tag> visible,Collection<Tag> selected){HashSet<String> visibleIds=new HashSet<>();for(Tag t:visible)visibleIds.add(t.id);for(Iterator<String> it=ids.iterator();it.hasNext();)if(visibleIds.contains(it.next()))it.remove();for(String id:visibleIds)names.remove(id);for(Tag t:selected)if(!ids.contains(t.id)){ids.add(t.id);names.put(t.id,t.name);}}
 static String labels(List<String> ids,Map<String,String> names,TagRepository repo){ArrayList<String> out=new ArrayList<>();for(String id:ids){Tag t=repo==null?null:repo.find(id);String n=t==null?names.get(id):t.name;if(n!=null&&!n.trim().isEmpty())out.add(n);}return String.join(" · ",out);}
 private static void replaceEmbedded(List<Trip> trips,String id,String name){for(Trip t:trips){if(t.tagIds.contains(id))t.tagNames.put(id,name);for(Trip.Stop s:t.stops)if(s.tagIds.contains(id))s.tagNames.put(id,name);}}
 private static void detach(ArrayList<String> ids,Map<String,String> names,String id){ids.remove(id);names.remove(id);} private static String clean(String s){s=s==null?"":s.trim();if(s.isEmpty()||s.length()>40)throw new IllegalArgumentException("标签名称应为 1–40 个字");return s;}
 private static void unique(List<Tag> tags,String id,String name){for(Tag t:tags)if(!t.id.equals(id)&&t.name.equalsIgnoreCase(name))throw new IllegalArgumentException("标签名称已存在");}private static void uniqueGroups(List<Group> groups,String id,String name){for(Group g:groups)if(!g.id.equals(id)&&g.name.equalsIgnoreCase(name))throw new IllegalArgumentException("标签组名称已存在");}
 private static Tag need(State s,String id){Tag t=find(s.tags,id);if(t==null)throw new IllegalArgumentException("标签不存在");return t;}private static Group needGroup(State s,String id){for(Group g:s.groups)if(g.id.equals(id))return g;throw new IllegalArgumentException("标签组不存在");}private static Tag find(List<Tag> tags,String id){for(Tag t:tags)if(t.id.equals(id))return t;return null;}
 private static void setGroups(State s,Tag t,Collection<String> ids){for(String id:ids)if(groupIn(s,id)!=null&&!t.groupIds.contains(id))t.groupIds.add(id);}private static Group groupIn(State s,String id){for(Group g:s.groups)if(g.id.equals(id))return g;return null;}
 private State state(){String raw=prefs.getString(REGISTRY,null);if(raw!=null){try{return read(new JSONObject(raw));}catch(Exception e){throw new IllegalStateException("标签注册表损坏，请从备份恢复");}}State s=initial();write(s);return s;}
 private State initial(){State s=new State();s.groups.addAll(presetGroups());s.tags.addAll(legacy());for(Tag t:presetTags())if(findByName(s.tags,t.name)==null)s.tags.add(t);try{JSONArray old=new JSONArray(prefs.getString(KEY,"[]"));for(int i=0;i<old.length();i++){JSONObject o=old.getJSONObject(i);String id=o.optString("id"),name=o.optString("name").trim();if(!id.isEmpty()&&!name.isEmpty()&&find(s.tags,id)==null&&findByName(s.tags,name)==null)s.tags.add(new Tag(id,name,o.optInt("color",DEFAULT_COLOR),false));}}catch(Exception ignored){}return s;}
 private static Tag findByName(List<Tag> tags,String name){for(Tag t:tags)if(t.name.equalsIgnoreCase(name))return t;return null;} private static final class State {final ArrayList<Tag> tags=new ArrayList<>();final ArrayList<Group> groups=new ArrayList<>();final HashSet<String> deletedSystemIds=new HashSet<>();}
 private static State read(JSONObject o)throws JSONException{State s=new State();JSONArray gs=o.optJSONArray("groups"),ts=o.optJSONArray("tags"),deleted=o.optJSONArray("deletedSystemIds");if(gs==null||ts==null||gs.length()>MAX_GROUPS||ts.length()>MAX_TAGS||(deleted!=null&&deleted.length()>10000))throw new IllegalArgumentException("标签数量无效");if(deleted!=null)for(int i=0;i<deleted.length();i++)s.deletedSystemIds.add(boundedId(deleted.optString(i)));HashSet<String> ids=new HashSet<>(),names=new HashSet<>();for(int i=0;i<gs.length();i++){JSONObject x=gs.getJSONObject(i);String id=boundedId(x.optString("id")),n=clean(x.optString("name"));if(!ids.add(id)||!names.add(n.toLowerCase(Locale.ROOT)))throw new IllegalArgumentException("标签组重复");s.groups.add(new Group(id,n,Trip.bounded(x.optString("description"),120),x.optBoolean("system")));}ids.clear();names.clear();for(int i=0;i<ts.length();i++){JSONObject x=ts.getJSONObject(i);String id=boundedId(x.optString("id")),n=clean(x.optString("name"));if(s.deletedSystemIds.contains(id)||!ids.add(id)||!names.add(n.toLowerCase(Locale.ROOT)))throw new IllegalArgumentException("标签重复");Tag t=new Tag(id,n,x.optInt("color",DEFAULT_COLOR),x.optBoolean("system"));JSONArray a=x.optJSONArray("groupIds");if(a!=null){if(a.length()>MAX_GROUPS)throw new IllegalArgumentException("标签分组过多");for(int k=0;k<a.length();k++){String gid=boundedId(a.optString(k));if(groupIn(s,gid)!=null&&!t.groupIds.contains(gid))t.groupIds.add(gid);}}s.tags.add(t);}return s;}
 private static String boundedId(String id){id=id==null?"":id.trim();if(id.isEmpty()||id.length()>100)throw new IllegalArgumentException("标签 ID 无效");return id;}
 private static Group findGroup(List<Group> groups,String id){for(Group g:groups)if(g.id.equals(id))return g;return null;}private static Group findGroupByName(List<Group> groups,String name){for(Group g:groups)if(g.name.equalsIgnoreCase(name))return g;return null;}
 private static JSONObject encode(State s)throws JSONException{JSONArray ts=new JSONArray(),gs=new JSONArray(),deleted=new JSONArray();for(String id:s.deletedSystemIds)deleted.put(id);for(Group g:s.groups)gs.put(new JSONObject().put("id",g.id).put("name",g.name).put("description",g.description).put("system",g.system));for(Tag t:s.tags){JSONArray a=new JSONArray();for(String id:t.groupIds)a.put(id);ts.put(new JSONObject().put("id",t.id).put("name",t.name).put("color",t.color).put("system",t.system).put("groupIds",a));}return new JSONObject().put("groups",gs).put("tags",ts).put("deletedSystemIds",deleted);}
 private void write(State s){try{prefs.edit().putString(REGISTRY,encode(s).toString()).apply();}catch(Exception e){throw new IllegalStateException("标签保存失败");}}
 private static List<Group> presetGroups(){return Arrays.asList(new Group("sys-preset-1","系统预设一（详细）","按旅行主题细分选择",true),new Group("sys-preset-2","系统预设二（简洁）","简洁通用的旅行分类",true));}
 private static List<Tag> legacy(){return Arrays.asList(tag("sys-food","美食",0xffE07A5F,"sys-preset-2"),tag("sys-nature","自然",0xff4F9D69),tag("sys-culture","人文",0xff8064A2,"sys-preset-2"),tag("sys-family","亲子",0xff3D85C6,"sys-preset-2"),tag("sys-shopping","购物",0xffD6A84B,"sys-preset-2"));}
 private static List<Tag> presetTags(){String[] names={"自然风光","人文历史","城市漫游","古迹遗址","建筑设计","艺术文化","公园园林","海滨水景","山野秘境","美食探索","咖啡小憩","购物逛街","娱乐体验","休闲度假","夜景夜游","摄影打卡","小众探索","民俗体验","宗教文化","亲子游玩","户外运动","观景胜地","季节限定","特色地标"};String[] ids={"scenery","history","city-walk","heritage","architecture","art","park","seaside","wild","food-explore","coffee","shopping-walk","entertainment","resort","night","photo","hidden","folk","religion","family-play","outdoor","view","season","landmark"};ArrayList<Tag> out=new ArrayList<>();for(int i=0;i<names.length;i++)out.add(tag("sys-p1-"+ids[i],names[i],DEFAULT_COLOR,"sys-preset-1"));out.add(tag("sys-scenery","风景",0xff4F9D69,"sys-preset-2"));out.add(tag("sys-city","城市",0xff3D85C6,"sys-preset-2"));out.add(tag("sys-leisure","休闲",0xff8064A2,"sys-preset-2"));out.add(tag("sys-outdoor","户外",0xff4F9D69,"sys-preset-2"));return out;}
 private static Tag tag(String id,String name,int color,String... groups){Tag t=new Tag(id,name,color,true);t.groupIds.addAll(Arrays.asList(groups));return t;}
}
