package cn.lvxu.travel;
import android.app.*;import android.widget.*;import java.util.*;
/** Reusable chooser for trips and stops. Changes are only applied after 确定. */
final class TagUi {
 interface Applied {void onApplied();} private static final int[] COLORS={0xffE07A5F,0xff3D85C6,0xff8064A2,0xffD6A84B,0xff4F9D69,0xff829399};
 static void tripPicker(MainActivity a,Trip t,boolean multi,Applied done){picker(a,t.tagIds,t.tagNames,multi,done);}static void stopPicker(MainActivity a,Trip.Stop s,boolean multi,Applied done){picker(a,s.tagIds,s.tagNames,multi,done);}
 private static void picker(MainActivity a,ArrayList<String> ids,LinkedHashMap<String,String> names,boolean multi,Applied done){TagChooser.show(a,ids,names,multi,done);}
 static void manage(MainActivity a,TagRepository repo,Applied done){String[] choices={"＋ 新建标签","＋ 新建标签组","编辑标签","编辑标签组"};new RoundedDialogs.Builder(a).setTitle("标签与标签组管理").setItems(choices,(d,i)->{if(i==0)editTag(a,repo,null,done);else if(i==1)editGroup(a,repo,null,done);else if(i==2)chooseTag(a,repo,done);else chooseGroup(a,repo,done);}).show();}
 private static void chooseTag(MainActivity a,TagRepository repo,Applied done){ArrayList<TagRepository.Tag> tags=new ArrayList<>(repo.all());String[] names=new String[tags.size()];for(int i=0;i<names.length;i++)names[i]=tags.get(i).name;new RoundedDialogs.Builder(a).setTitle("编辑标签").setItems(names,(d,i)->editTag(a,repo,tags.get(i),done)).show();}
 private static void chooseGroup(MainActivity a,TagRepository repo,Applied done){ArrayList<TagRepository.Group> groups=new ArrayList<>(repo.groups());String[] names=new String[groups.size()];for(int i=0;i<names.length;i++)names[i]=groups.get(i).name;new RoundedDialogs.Builder(a).setTitle("编辑标签组").setItems(names,(d,i)->editGroup(a,repo,groups.get(i),done)).show();}
 private static void editTag(MainActivity a,TagRepository repo,TagRepository.Tag old,Applied done){LinearLayout f=a.col();EditText name=a.field(f,"标签名称",old==null?"":old.name,1);String[] colors={"珊瑚","蓝色","紫色","金色","绿色","灰色"};Spinner color=a.select(f,"颜色",colors,colors[old==null?5:colorIndex(old.color)]);a.dialog(old==null?"新建标签":"编辑标签",f,()->{if(old==null)repo.create(name.getText().toString(),COLORS[color.getSelectedItemPosition()]);else{repo.rename(old.id,name.getText().toString(),COLORS[color.getSelectedItemPosition()],a.trips);a.changed();}done.onApplied();},old==null?null:()->{repo.delete(old.id,a.trips);a.changed();done.onApplied();});}
 private static void editGroup(MainActivity a,TagRepository repo,TagRepository.Group old,Applied done){LinearLayout f=a.col();EditText name=a.field(f,"标签组名称",old==null?"":old.name,1),description=a.field(f,"说明（可选）",old==null?"":old.description,1);ArrayList<TagRepository.Tag> tags=new ArrayList<>(repo.all());ArrayList<CheckBox> boxes=new ArrayList<>();for(TagRepository.Tag t:tags){CheckBox b=new CheckBox(a);b.setText(t.name);b.setChecked(old!=null&&t.groupIds.contains(old.id));f.addView(b);boxes.add(b);}a.dialog(old==null?"新建标签组":"编辑标签组",f,()->{ArrayList<String> selected=new ArrayList<>();for(int i=0;i<boxes.size();i++)if(boxes.get(i).isChecked())selected.add(tags.get(i).id);if(old==null){TagRepository.Group g=repo.createGroup(name.getText().toString(),description.getText().toString());repo.editGroup(g.id,g.name,g.description,selected);}else repo.editGroup(old.id,name.getText().toString(),description.getText().toString(),selected);done.onApplied();},old==null?null:()->{repo.deleteGroup(old.id);done.onApplied();});}
 private static int indexOf(boolean[] x){for(int i=0;i<x.length;i++)if(x[i])return i;return -1;}private static int colorIndex(int c){for(int i=0;i<COLORS.length;i++)if(COLORS[i]==c)return i;return 5;}
}
