package cn.lvxu.travel;
import android.app.*;import android.widget.*;import java.util.*;
/** Reusable chooser for trips and stops. Changes are only applied after 确定. */
final class TagUi {
 interface Applied {void onApplied();} private static final int[] COLORS={0xffE07A5F,0xff3D85C6,0xff8064A2,0xffD6A84B,0xff4F9D69,0xff829399};
 static void tripPicker(MainActivity a,Trip t,boolean multi,Applied done){picker(a,t.tagIds,t.tagNames,multi,done);}static void stopPicker(MainActivity a,Trip.Stop s,boolean multi,Applied done){picker(a,s.tagIds,s.tagNames,multi,done);}
 private static void picker(MainActivity a,ArrayList<String> ids,LinkedHashMap<String,String> names,boolean multi,Applied done){TagRepository repo=new TagRepository(a);ArrayList<TagRepository.Group> groups=new ArrayList<>(repo.groups());String[] choices=new String[groups.size()+1];int preferred=0;choices[0]="全部标签";for(int i=0;i<groups.size();i++){choices[i+1]=groups.get(i).name+" · "+groups.get(i).description;if("sys-preset-2".equals(groups.get(i).id))preferred=i+1;}new AlertDialog.Builder(a).setTitle("选择标签组").setSingleChoiceItems(choices,preferred,(d,w)->{d.dismiss();showTags(a,repo,w==0?null:groups.get(w-1),ids,names,multi,done);}).setNeutralButton("管理标签和标签组",(d,w)->manage(a,repo,done)).setNegativeButton("取消",null).show();}
 private static void showTags(MainActivity a,TagRepository repo,TagRepository.Group group,ArrayList<String> ids,LinkedHashMap<String,String> names,boolean multi,Applied done){ArrayList<TagRepository.Tag> visible=new ArrayList<>(repo.inGroup(group==null?null:group.id));boolean[] checked=new boolean[visible.size()];String[] labels=new String[visible.size()];for(int i=0;i<visible.size();i++){TagRepository.Tag t=visible.get(i);checked[i]=ids.contains(t.id);labels[i]=t.name+" · "+repo.description(t)+(t.system?"":"（自定义）");}AlertDialog.Builder b=new AlertDialog.Builder(a).setTitle((group==null?"全部标签":group.name)+(multi?"":"（单选）"));if(multi)b.setMultiChoiceItems(labels,checked,(d,w,on)->checked[w]=on);else b.setSingleChoiceItems(labels,indexOf(checked),(d,w)->{Arrays.fill(checked,false);checked[w]=true;});b.setNeutralButton("返回标签组",null).setNegativeButton("取消",null).setPositiveButton("确定",null);AlertDialog d=b.create();d.setOnShowListener(v->{d.getButton(AlertDialog.BUTTON_NEUTRAL).setOnClickListener(x->{d.dismiss();picker(a,ids,names,multi,done);});d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(x->{ArrayList<TagRepository.Tag> selected=new ArrayList<>();for(int i=0;i<checked.length;i++)if(checked[i])selected.add(visible.get(i));if(group==null)TagRepository.assign(ids,names,selected);else TagRepository.assignGroup(ids,names,visible,selected);d.dismiss();done.onApplied();});});d.show();}
 static void manage(MainActivity a,TagRepository repo,Applied done){String[] choices={"＋ 新建标签","＋ 新建标签组","编辑标签","编辑标签组"};new AlertDialog.Builder(a).setTitle("标签与标签组管理").setItems(choices,(d,i)->{if(i==0)editTag(a,repo,null,done);else if(i==1)editGroup(a,repo,null,done);else if(i==2)chooseTag(a,repo,done);else chooseGroup(a,repo,done);}).show();}
 private static void chooseTag(MainActivity a,TagRepository repo,Applied done){ArrayList<TagRepository.Tag> tags=new ArrayList<>(repo.all());String[] names=new String[tags.size()];for(int i=0;i<names.length;i++)names[i]=tags.get(i).name;new AlertDialog.Builder(a).setTitle("编辑标签").setItems(names,(d,i)->editTag(a,repo,tags.get(i),done)).show();}
 private static void chooseGroup(MainActivity a,TagRepository repo,Applied done){ArrayList<TagRepository.Group> groups=new ArrayList<>(repo.groups());String[] names=new String[groups.size()];for(int i=0;i<names.length;i++)names[i]=groups.get(i).name;new AlertDialog.Builder(a).setTitle("编辑标签组").setItems(names,(d,i)->editGroup(a,repo,groups.get(i),done)).show();}
 private static void editTag(MainActivity a,TagRepository repo,TagRepository.Tag old,Applied done){LinearLayout f=a.col();EditText name=a.field(f,"标签名称",old==null?"":old.name,1);String[] colors={"珊瑚","蓝色","紫色","金色","绿色","灰色"};Spinner color=a.select(f,"颜色",colors,colors[old==null?5:colorIndex(old.color)]);a.dialog(old==null?"新建标签":"编辑标签",f,()->{if(old==null)repo.create(name.getText().toString(),COLORS[color.getSelectedItemPosition()]);else{repo.rename(old.id,name.getText().toString(),COLORS[color.getSelectedItemPosition()],a.trips);a.changed();}done.onApplied();},old==null?null:()->{repo.delete(old.id,a.trips);a.changed();done.onApplied();});}
 private static void editGroup(MainActivity a,TagRepository repo,TagRepository.Group old,Applied done){LinearLayout f=a.col();EditText name=a.field(f,"标签组名称",old==null?"":old.name,1),description=a.field(f,"说明（可选）",old==null?"":old.description,1);ArrayList<TagRepository.Tag> tags=new ArrayList<>(repo.all());ArrayList<CheckBox> boxes=new ArrayList<>();for(TagRepository.Tag t:tags){CheckBox b=new CheckBox(a);b.setText(t.name);b.setChecked(old!=null&&t.groupIds.contains(old.id));f.addView(b);boxes.add(b);}a.dialog(old==null?"新建标签组":"编辑标签组",f,()->{ArrayList<String> selected=new ArrayList<>();for(int i=0;i<boxes.size();i++)if(boxes.get(i).isChecked())selected.add(tags.get(i).id);if(old==null){TagRepository.Group g=repo.createGroup(name.getText().toString(),description.getText().toString());repo.editGroup(g.id,g.name,g.description,selected);}else repo.editGroup(old.id,name.getText().toString(),description.getText().toString(),selected);done.onApplied();},old==null?null:()->{repo.deleteGroup(old.id);done.onApplied();});}
 private static int indexOf(boolean[] x){for(int i=0;i<x.length;i++)if(x[i])return i;return -1;}private static int colorIndex(int c){for(int i=0;i<COLORS.length;i++)if(COLORS[i]==c)return i;return 5;}
}
