package cn.lvxu.travel;
import android.app.*;import android.graphics.Color;import android.text.*;import android.view.Gravity;import android.widget.*;import org.json.*;
/** Palette edits are drafts until the explicit save action. */
final class ThemeSettingsUi {
 private final MainActivity a;
 ThemeSettingsUi(MainActivity a){this.a=a;}
 void show(Runnable applied){LinearLayout body=a.col();a.pad(body,20);ScrollView scroll=new ScrollView(a);scroll.addView(body);final String[] selected={a.prefs.colorPreset()};final boolean[] dark={MainActivity.DARK};AlertDialog dialog=new RoundedDialogs.Builder(a).asSelection().setTitle("颜色设置").setView(scroll).setNegativeButton("取消",null).setPositiveButton("应用预设",null).create();
 body.addView(a.text("选择双色搭配，或分别自定义浅色与深色。更改只影响外观。",13,MainActivity.MUTED));Switch mode=new Switch(a);mode.setText("预览深色效果");mode.setTextColor(MainActivity.INK);mode.setChecked(dark[0]);body.addView(mode);LinearLayout demo=a.col();body.addView(demo);a.space(body,10);LinearLayout choices=a.col();body.addView(choices);Runnable render=()->renderChoices(choices,demo,selected,dark);render.run();mode.setOnCheckedChangeListener((v,on)->{dark[0]=on;render.run();});a.space(body,6);body.addView(a.text(a.prefs.customColorsEnabled()?"当前使用自定义颜色":"自定义支持 #RRGGBB，保留两种模式各自的颜色。",13,MainActivity.MUTED));body.addView(a.action("自定义浅色颜色",false,()->custom(false,dialog,applied)));a.space(body,8);body.addView(a.action("自定义深色颜色",false,()->custom(true,dialog,applied)));a.space(body,8);body.addView(a.action("恢复原绿配色",false,()->new RoundedDialogs.Builder(a).setTitle("恢复原绿配色？").setMessage("将清除自定义颜色，旅行与图片不受影响。").setNegativeButton("取消",null).setPositiveButton("恢复",(d,w)->{a.prefs.resetColors();dialog.dismiss();applied.run();}).show()));dialog.setOnShowListener(v->dialog.getButton(-1).setOnClickListener(w->{a.prefs.setColorPreset(selected[0]);dialog.dismiss();applied.run();}));dialog.show(); }
 private void renderChoices(LinearLayout choices,LinearLayout demo,String[] selected,boolean[] dark){demo.removeAllViews();demo.addView(sample(ThemeColors.preset(selected[0],dark[0])));choices.removeAllViews();for(int i=0;i<ThemeColors.IDS.length;i++){final String id=ThemeColors.IDS[i];int[] colors=ThemeColors.preset(id,dark[0]);LinearLayout row=a.row();a.pad(row,12);android.graphics.drawable.GradientDrawable shape=a.shape(colors[0],14);shape.setStroke(a.dp(selected[0].equals(id)?2:1),selected[0].equals(id)?MainActivity.GREEN:MainActivity.LINE);row.setBackground(shape);TextView name=a.bold((selected[0].equals(id)?"✓ ":"")+ThemeColors.NAMES[i],15,MainActivity.readable(colors[2],colors[0]));row.addView(name,new LinearLayout.LayoutParams(0,-2,1));for(int color:new int[]{colors[4],colors[5],colors[1]}){android.view.View dot=new android.view.View(a);android.graphics.drawable.GradientDrawable fill=a.shape(color,20);fill.setStroke(a.dp(1),colors[6]);dot.setBackground(fill);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(a.dp(22),a.dp(22));lp.leftMargin=a.dp(7);row.addView(dot,lp);}row.setContentDescription("配色："+ThemeColors.NAMES[i]);row.setOnClickListener(v->{selected[0]=id;renderChoices(choices,demo,selected,dark);});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.bottomMargin=a.dp(8);choices.addView(row,lp);}}
 private LinearLayout sample(int[] c){LinearLayout preview=a.col();preview.setBackground(a.shape(c[1],12));a.pad(preview,12);preview.addView(a.bold("下一程，随心出发",15,MainActivity.readable(c[2],c[1])));preview.addView(a.text("旅行 · 地点 · 回忆",12,MainActivity.readable(c[3],c[1])));a.space(preview,10);LinearLayout buttons=a.row();TextView first=a.text("主要按钮",12,ThemeColors.onColor(c[4])),second=a.text("浅色按钮",12,MainActivity.readable(c[2],c[5]));for(TextView t:new TextView[]{first,second}){t.setGravity(Gravity.CENTER);a.pad(t,10);}first.setBackground(a.shape(c[4],12));second.setBackground(a.shape(c[5],12));buttons.addView(first,new LinearLayout.LayoutParams(0,-2,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-2,1);lp.leftMargin=a.dp(8);buttons.addView(second,lp);preview.addView(buttons);return preview;}
 private void custom(boolean dark,AlertDialog parent,Runnable applied){String mode=dark?"dark":"light";JSONObject all=a.prefs.customColors();int[] current=ThemeColors.resolve(a.prefs.colorPreset(),dark,all.optJSONObject(mode));LinearLayout form=a.col();a.pad(form,20);ScrollView scroll=new ScrollView(a);scroll.addView(form);form.addView(a.text("输入六位十六进制颜色，如 #B85882。文字对比不足时会自动调整为可读颜色。",13,MainActivity.MUTED));LinearLayout preview=a.col();form.addView(preview);EditText[] fields=new EditText[ThemeColors.KEYS.length];for(int i=0;i<fields.length;i++)fields[i]=a.field(form,ThemeColors.LABELS[i],ThemeColors.hex(current[i]),InputType.TYPE_CLASS_TEXT);TextView error=a.text("",13,MainActivity.ORANGE);form.addView(error);Runnable update=()->{try{JSONObject values=read(fields);int[] c=ThemeColors.resolve(a.prefs.colorPreset(),dark,values);preview.removeAllViews();preview.setBackground(a.shape(c[0],16));a.pad(preview,12);preview.addView(sample(c));error.setText("");}catch(Exception e){error.setText("请输入完整的六位颜色编码，再预览或保存。");}};for(EditText f:fields)f.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int start,int count,int after){}public void onTextChanged(CharSequence s,int start,int before,int count){update.run();}public void afterTextChanged(Editable e){}});AlertDialog d=new RoundedDialogs.Builder(a).setTitle(dark?"自定义深色配色":"自定义浅色配色").setView(scroll).setNegativeButton("取消",null).setPositiveButton("保存",null).create();d.setOnShowListener(v->d.getButton(-1).setOnClickListener(w->{try{JSONObject values=read(fields);all.put(mode,values);a.prefs.setCustomColors(all);d.dismiss();parent.dismiss();applied.run();}catch(Exception e){error.setText(e.getMessage()==null?"颜色格式无效":e.getMessage());a.toast("颜色未保存，请检查输入");}}));update.run();d.show();}
 private JSONObject read(EditText[] fields)throws JSONException{JSONObject out=new JSONObject();for(int i=0;i<fields.length;i++){String value=fields[i].getText().toString().trim();try{out.put(ThemeColors.KEYS[i],ThemeColors.hex(ThemeColors.parseHex(value)));fields[i].setError(null);}catch(IllegalArgumentException e){fields[i].setError("请输入 #RRGGBB");throw e;}}return out;}
}
