package cn.lvxu.travel;
import android.content.*;import android.database.Cursor;import android.database.sqlite.*;import org.json.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;
/** Transactional SQLite snapshot store with one-time migration from trips-v1.json. */
final class TripStore extends SQLiteOpenHelper {
 private final Context context; private static final String DB="trips-v2.db",LEGACY="trips-v1.json";
 TripStore(Context c){super(c,DB,null,1);context=c.getApplicationContext();}
 @Override public void onCreate(SQLiteDatabase db){db.execSQL("CREATE TABLE snapshot (id INTEGER PRIMARY KEY CHECK(id=1), json TEXT NOT NULL, updated_at INTEGER NOT NULL)");}
 @Override public void onUpgrade(SQLiteDatabase db,int oldVersion,int newVersion){}
 boolean exists(){Cursor c=getReadableDatabase().rawQuery("SELECT 1 FROM snapshot WHERE id=1",null);try{if(c.moveToFirst())return true;}finally{c.close();}File f=new File(context.getFilesDir(),LEGACY);return f.exists()||new File(f+".bak").exists();}
 static String encode(List<Trip> ts)throws JSONException{JSONArray a=new JSONArray();for(Trip t:ts){JSONObject o=t.json();o.put("pinned",t.pinned).put("archived",t.archived).put("favorite",t.favorite).put("updatedAt",t.updatedAt);a.put(o);}return new JSONObject().put("schema",3).put("trips",a).toString(2);}
 static ArrayList<Trip> decode(String text)throws JSONException{JSONObject o=new JSONObject(text);int schema=o.optInt("schema",1);if(schema<1||schema>3)throw new IllegalArgumentException("不支持此备份版本");JSONArray a=o.getJSONArray("trips");if(a.length()>100)throw new IllegalArgumentException("最多 100 个行程");ArrayList<Trip> out=new ArrayList<>();HashSet<String> ids=new HashSet<>();for(int k=0;k<a.length();k++){JSONObject raw=a.getJSONObject(k);Trip t=Trip.from(raw);t.pinned=raw.optBoolean("pinned",false);t.archived=raw.optBoolean("archived",false);t.favorite=raw.optBoolean("favorite",false);t.updatedAt=raw.optLong("updatedAt",System.currentTimeMillis());if(!ids.add(t.id))throw new IllegalArgumentException("行程 ID 重复");out.add(t);}sort(out);return out;}
 static void sort(List<Trip> ts){ts.sort((a,b)->{if(a.pinned!=b.pinned)return a.pinned?-1:1;if(a.favorite!=b.favorite)return a.favorite?-1:1;return Long.compare(b.updatedAt,a.updatedAt);});}
 ArrayList<Trip> read()throws Exception{SQLiteDatabase db=getWritableDatabase();int size=-1;Cursor c=db.rawQuery("SELECT length(json) FROM snapshot WHERE id=1",null);try{if(c.moveToFirst())size=c.getInt(0);}finally{c.close();}if(size>=0){if(size>16*1024*1024)throw new UnreadableSnapshotException("本地数据超出读取范围",null);StringBuilder raw=new StringBuilder(size);for(int offset=1;offset<=size;offset+=65536){Cursor chunk=db.rawQuery("SELECT substr(json,?,65536) FROM snapshot WHERE id=1",new String[]{String.valueOf(offset)});try{if(!chunk.moveToFirst())throw new IOException("本地数据读取中断");raw.append(chunk.getString(0));}finally{chunk.close();}}return decodeLocal(raw.toString());}File legacy=new File(context.getFilesDir(),LEGACY);if(!legacy.exists()){File b=new File(legacy+".bak");if(b.exists())legacy=b;}if(!legacy.exists())throw new FileNotFoundException();String raw=new String(readBounded(legacy),StandardCharsets.UTF_8);ArrayList<Trip> migrated=decodeLocal(raw);save(migrated);return migrated;}
 private static ArrayList<Trip> decodeLocal(String raw)throws UnreadableSnapshotException {try{return decode(raw);}catch(JSONException|RuntimeException e){throw new UnreadableSnapshotException("本地旅行内容无法读取",e);}}
 /** An explicit recovery may replace invalid snapshot content, never ordinary database/I/O failures. */
 ArrayList<Trip> readForRestore(boolean allowUnreadable)throws Exception {
  try{return read();}catch(UnreadableSnapshotException e){if(!allowUnreadable)throw e;preserveRecoveryEvidence();return new ArrayList<>();}
 }
 private static final class UnreadableSnapshotException extends IOException {UnreadableSnapshotException(String message,Throwable cause){super(message,cause);}}
 private void preserveRecoveryEvidence()throws Exception {
  File evidence=new File(context.getFilesDir(),"recovery/restore-"+UUID.randomUUID());if(!evidence.mkdirs())throw new IOException("无法保留损坏数据，恢复已停止");
  // Keep the original filenames together so the DB/WAL can be inspected as one bundle later.
  File database=context.getDatabasePath(DB);for(String suffix:new String[]{"","-wal","-shm","-journal"})copyEvidence(new File(database.getPath()+suffix),new File(evidence,DB+suffix));
  for(String suffix:new String[]{"",".bak"})copyEvidence(new File(context.getFilesDir(),LEGACY+suffix),new File(evidence,LEGACY+suffix));
  SQLiteDatabase db=getReadableDatabase();int size=-1;Cursor count=db.rawQuery("SELECT length(json) FROM snapshot WHERE id=1",null);try{if(count.moveToFirst())size=count.getInt(0);}finally{count.close();}
  if(size>=0)try(Writer out=new OutputStreamWriter(new FileOutputStream(new File(evidence,"snapshot.json")),StandardCharsets.UTF_8)){for(int offset=1;offset<=size;offset+=65536){Cursor chunk=db.rawQuery("SELECT substr(json,?,65536) FROM snapshot WHERE id=1",new String[]{String.valueOf(offset)});try{if(!chunk.moveToFirst())throw new IOException("损坏快照保留中断，恢复已停止");out.write(chunk.getString(0));}finally{chunk.close();}}}
 }
 private static void copyEvidence(File source,File target)throws IOException {if(source.exists()){if(!source.isFile())throw new IOException("原数据文件无法保留，恢复已停止");java.nio.file.Files.copy(source.toPath(),target.toPath());}}
 void save(List<Trip> ts)throws Exception{String json=encode(ts);if(json.getBytes(StandardCharsets.UTF_8).length>16*1024*1024)throw new IOException("行程文字数据已超过 16 MB，请先备份并整理旧旅行");decode(json);SQLiteDatabase db=getWritableDatabase();db.beginTransaction();try{ContentValues v=new ContentValues();v.put("id",1);v.put("json",json);v.put("updated_at",System.currentTimeMillis());if(db.insertWithOnConflict("snapshot",null,v,SQLiteDatabase.CONFLICT_REPLACE)<0)throw new IOException("数据库写入失败");db.setTransactionSuccessful();}finally{db.endTransaction();}}
 private static byte[] readBounded(File f)throws IOException{try(InputStream in=new FileInputStream(f);ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1){out.write(b,0,n);if(out.size()>5*1024*1024)throw new UnreadableSnapshotException("数据文件过大",null);}return out.toByteArray();}}
}
