package cn.lvxu.travel;
import android.content.*;import android.database.Cursor;import android.database.sqlite.*;import org.json.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;
/** Transactional SQLite snapshot store with one-time migration from trips-v1.json. */
final class TripStore extends SQLiteOpenHelper {
 private final Context context; private static final String DB="trips-v2.db",LEGACY="trips-v1.json";
 TripStore(Context c){super(c,DB,null,1);context=c.getApplicationContext();}
 @Override public void onCreate(SQLiteDatabase db){db.execSQL("CREATE TABLE snapshot (id INTEGER PRIMARY KEY CHECK(id=1), json TEXT NOT NULL, updated_at INTEGER NOT NULL)");}
 @Override public void onUpgrade(SQLiteDatabase db,int oldVersion,int newVersion){}
 boolean exists(){Cursor c=getReadableDatabase().rawQuery("SELECT 1 FROM snapshot WHERE id=1",null);try{if(c.moveToFirst())return true;}finally{c.close();}File f=new File(context.getFilesDir(),LEGACY);return f.exists()||new File(f+".bak").exists();}
 static String encode(List<Trip> ts)throws JSONException{JSONArray a=new JSONArray();for(Trip t:ts){JSONObject o=t.json();o.put("pinned",t.pinned).put("archived",t.archived).put("favorite",t.favorite).put("updatedAt",t.updatedAt);a.put(o);}return new JSONObject().put("schema",2).put("trips",a).toString(2);}
 static ArrayList<Trip> decode(String text)throws JSONException{JSONObject o=new JSONObject(text);int schema=o.optInt("schema",1);if(schema<1||schema>2)throw new IllegalArgumentException("不支持此备份版本");JSONArray a=o.getJSONArray("trips");if(a.length()>100)throw new IllegalArgumentException("最多 100 个行程");ArrayList<Trip> out=new ArrayList<>();HashSet<String> ids=new HashSet<>();for(int k=0;k<a.length();k++){JSONObject raw=a.getJSONObject(k);Trip t=Trip.from(raw);t.pinned=raw.optBoolean("pinned",false);t.archived=raw.optBoolean("archived",false);t.favorite=raw.optBoolean("favorite",false);t.updatedAt=raw.optLong("updatedAt",System.currentTimeMillis());if(!ids.add(t.id))throw new IllegalArgumentException("行程 ID 重复");out.add(t);}sort(out);return out;}
 static void sort(List<Trip> ts){ts.sort((a,b)->{if(a.pinned!=b.pinned)return a.pinned?-1:1;if(a.favorite!=b.favorite)return a.favorite?-1:1;return Long.compare(b.updatedAt,a.updatedAt);});}
 ArrayList<Trip> read()throws Exception{SQLiteDatabase db=getWritableDatabase();int size=-1;Cursor c=db.rawQuery("SELECT length(json) FROM snapshot WHERE id=1",null);try{if(c.moveToFirst())size=c.getInt(0);}finally{c.close();}if(size>=0){if(size>16*1024*1024)throw new IOException("本地数据超出读取范围");StringBuilder raw=new StringBuilder(size);for(int offset=1;offset<=size;offset+=65536){Cursor chunk=db.rawQuery("SELECT substr(json,?,65536) FROM snapshot WHERE id=1",new String[]{String.valueOf(offset)});try{if(!chunk.moveToFirst())throw new IOException("本地数据读取中断");raw.append(chunk.getString(0));}finally{chunk.close();}}return decode(raw.toString());}File legacy=new File(context.getFilesDir(),LEGACY);if(!legacy.exists()){File b=new File(legacy+".bak");if(b.exists())legacy=b;}if(!legacy.exists())throw new FileNotFoundException();String raw=new String(readBounded(legacy),StandardCharsets.UTF_8);ArrayList<Trip> migrated=decode(raw);save(migrated);return migrated;}
 void save(List<Trip> ts)throws Exception{String json=encode(ts);if(json.getBytes(StandardCharsets.UTF_8).length>16*1024*1024)throw new IOException("行程文字数据已超过 16 MB，请先备份并整理旧旅行");SQLiteDatabase db=getWritableDatabase();db.beginTransaction();try{ContentValues v=new ContentValues();v.put("id",1);v.put("json",json);v.put("updated_at",System.currentTimeMillis());if(db.insertWithOnConflict("snapshot",null,v,SQLiteDatabase.CONFLICT_REPLACE)<0)throw new IOException("数据库写入失败");db.setTransactionSuccessful();}finally{db.endTransaction();}}
 private static byte[] readBounded(File f)throws IOException{try(InputStream in=new FileInputStream(f);ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1){out.write(b,0,n);if(out.size()>5*1024*1024)throw new IOException("数据文件过大");}return out.toByteArray();}}
}
