package cn.lvxu.travel;
import android.content.Context;import okhttp3.*;import okio.BufferedSink;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.concurrent.TimeUnit;import java.util.regex.*;
/** HTTPS WebDAV transport. OkHttp is used because Android rejects PROPFIND in HttpURLConnection. */
public final class WebDavService{
 private static final MediaType XML=MediaType.get("application/xml; charset=utf-8"),ZIP=MediaType.get("application/zip");private final SecureVault vault;private final OkHttpClient client;
 public WebDavService(Context c){this(c,new OkHttpClient.Builder().connectTimeout(15,TimeUnit.SECONDS).readTimeout(45,TimeUnit.SECONDS).writeTimeout(45,TimeUnit.SECONDS).followRedirects(false).followSslRedirects(false).build());}WebDavService(Context c,OkHttpClient custom){vault=new SecureVault(c);client=custom;}
 public void configure(String endpoint,String user,String password)throws Exception{URL u=checked(endpoint);user=user==null?"":user;password=password==null?"":password;if(user.length()>256||password.length()>2048)throw new IOException("WebDAV 凭据过长");vault.put("url",u.toString());vault.put("user",user);vault.put("password",password);}
 public void configureAndTest(String endpoint,String user,String password)throws Exception{String oldUrl=vault.get("url"),oldUser=vault.get("user"),oldPassword=vault.get("password");configure(endpoint,user,password);try{test();}catch(Exception failure){try{if(oldUrl.isEmpty())clear();else configure(oldUrl,oldUser,oldPassword);}catch(Exception rollback){failure.addSuppressed(rollback);}throw failure;}}
 public boolean configured(){try{return!vault.get("url").isEmpty();}catch(Exception e){return false;}}public String endpoint(){try{return vault.get("url");}catch(Exception e){return"";}}public void clear(){vault.clear();}
 public void test()throws Exception{byte[] data="<?xml version=\"1.0\"?><propfind xmlns=\"DAV:\"><prop><displayname/></prop></propfind>".getBytes(StandardCharsets.UTF_8);try(Response r=execute("PROPFIND",endpoint(),RequestBody.create(data,XML),"0")){accept(r,200,207);}}
 public void upload(String name,InputStream input,long length)throws Exception{if(length<0||length>BackupArchive.MAX_ARCHIVE)throw new IOException("备份大小无效");RequestBody body=new RequestBody(){public MediaType contentType(){return ZIP;}public long contentLength(){return length;}public boolean isOneShot(){return true;}public void writeTo(BufferedSink sink)throws IOException{byte[] b=new byte[8192];long total=0;for(int n;(n=input.read(b))!=-1;){total+=n;if(total>length||total>BackupArchive.MAX_ARCHIVE)throw new IOException("上传内容大小与声明不一致");sink.write(b,0,n);}if(total!=length)throw new IOException("上传内容大小与声明不一致");}};try(Response r=execute("PUT",child(name),body,null)){accept(r,200,201,204);}}
 public void download(String name,OutputStream output)throws Exception{try(Response r=execute("GET",child(name),null,null)){accept(r,200);if(r.body()==null)throw new IOException("WebDAV 响应为空");try(InputStream in=r.body().byteStream()){copy(in,output,BackupArchive.MAX_ARCHIVE);}}}
 public List<String> list()throws Exception{byte[] data="<?xml version=\"1.0\"?><propfind xmlns=\"DAV:\"><prop><getcontentlength/></prop></propfind>".getBytes(StandardCharsets.UTF_8);String xml;try(Response r=execute("PROPFIND",endpoint(),RequestBody.create(data,XML),"1")){accept(r,207);xml=readBody(r,2*1024*1024);}ArrayList<String> names=new ArrayList<>();Matcher m=Pattern.compile("<(?:[^:>]+:)?href[^>]*>(.*?)</(?:[^:>]+:)?href>",Pattern.CASE_INSENSITIVE).matcher(xml);while(m.find()){String path=URLDecoder.decode(m.group(1).replace("&amp;","&"),"UTF-8");int slash=path.endsWith("/")?path.substring(0,path.length()-1).lastIndexOf('/'):path.lastIndexOf('/');String n=path.substring(slash+1);if(n.endsWith(".zip")&&n.matches("[A-Za-z0-9._-]{1,160}")&&!names.contains(n))names.add(n);}names.sort(Collections.reverseOrder());return names;}
 private Response execute(String method,String target,RequestBody body,String depth)throws Exception{checked(target);Request.Builder b=new Request.Builder().url(target).method(method,body).header("Authorization",Credentials.basic(vault.get("user"),vault.get("password"),StandardCharsets.UTF_8)).header("User-Agent","MaisuiTravel/2");if(depth!=null)b.header("Depth",depth);return client.newCall(b.build()).execute();}
 private String child(String n)throws Exception{if(n==null||!n.matches("[A-Za-z0-9._-]{1,160}"))throw new IOException("远端文件名无效");String base=endpoint();return(base.endsWith("/")?base:base+"/")+URLEncoder.encode(n,"UTF-8").replace("+","%20");}
 private static URL checked(String value)throws Exception{URL u=new URL(value);if(!"https".equalsIgnoreCase(u.getProtocol())||u.getUserInfo()!=null||u.getHost().isEmpty()||u.getQuery()!=null||u.getRef()!=null)throw new IOException("WebDAV 地址必须是无查询参数的 HTTPS 文件夹地址");return u;}
 private static void accept(Response r,int...allowed)throws IOException{for(int x:allowed)if(r.code()==x)return;String message="";try{message=readBody(r,4096);}catch(Exception ignored){}throw new IOException("WebDAV 返回 "+r.code()+(message.isEmpty()?"":"："+message.substring(0,Math.min(200,message.length()))));}
 private static String readBody(Response r,long max)throws IOException{if(r.body()==null)return"";try(InputStream in=r.body().byteStream();ByteArrayOutputStream out=new ByteArrayOutputStream()){copy(in,out,max);return out.toString("UTF-8");}}
 private static long copy(InputStream in,OutputStream out,long max)throws IOException{byte[] b=new byte[8192];long total=0;for(int n;(n=in.read(b))!=-1;){total+=n;if(total>max)throw new IOException("传输内容过大");out.write(b,0,n);}return total;}
}
