package cn.lvxu.travel;
import android.app.*;import android.content.*;import android.os.Bundle;import android.widget.*;import java.util.*;import java.io.*;import org.json.*;
/** Dedicated-emulator checks, invoked by the parent runner. Never call on a user's phone. */
final class AaLedgerAndroidTest {
 static int run(Instrumentation in)throws Exception {
  Context c=in.getTargetContext();TripStore store=new TripStore(c);ArrayList<Trip> original=store.read();MainActivity host=null;TestStartupGuard guard=new TestStartupGuard(c);int[] count={0};
  try{host=(MainActivity)in.startActivitySync(new Intent(c,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP));MainActivity a=host;FinanceUi finance=(FinanceUi)field(a,"finance");in.waitForIdleSync();Trip t=Trip.demo();t.budget=0;Trip.Member one=new Trip.Member();one.name="小王";Trip.Member two=new Trip.Member();two.name="小王";t.members.add(one);t.members.add(two);Trip.Expense bill=new Trip.Expense();bill.name="均摊餐费";bill.amount=101;bill.occurredAt="2026-10-06T12:00";bill.payerId=one.id;bill.shares.putAll(AaLedger.equal(101,Arrays.asList(one.id,two.id)));t.expenses.add(bill);Trip.Settlement paid=new Trip.Settlement();paid.fromId=two.id;paid.toId=one.id;paid.amount=20;paid.occurredAt="2026-10-06T13:00";t.settlements.add(paid);
   in.runOnMainSync(()->{a.trips.clear();a.trips.add(t);a.active=t;a.page=2;a.render();check(AuditHostUiTest.find(a.body,"尚未设置预算")!=null,"unset budget is not overspending",count);for(int i=0;i<65;i++){Trip.Expense e=new Trip.Expense();e.name="分页账单 "+i;e.occurredAt="2026-10-07T12:00";t.expenses.add(e);}a.render();check(AuditHostUiTest.find(a.body,"加载更多账单（剩余 36 笔）")!=null,"ledger initially limits rows",count);});
   in.runOnMainSync(()->{LinearLayout form=a.col();Trip single=Trip.demo();AaUi.ExpenseFields singleFields=new AaUi.ExpenseFields(a,form,single,null);check(singleFields.enabled==null,"single person no AA fields",count);AaUi.ExpenseFields edit=new AaUi.ExpenseFields(a,a.col(),t,bill);check(edit.enabled.isChecked()&&edit.participants.size()==2,"existing AA selections retained",count);Trip.Expense candidate=new Trip.Expense();candidate.amount=101;edit.apply(candidate);check(candidate.payerId.equals(one.id)&&candidate.shares.equals(bill.shares),"metadata edits keep exact fractions",count);Bundle state=new Bundle();edit.save(state);edit.enabled.setChecked(false);edit.participants.get(two.id).setChecked(false);edit.restore(state);check(edit.enabled.isChecked()&&edit.participants.get(two.id).isChecked(),"AA draft restores stable member selections",count);});
   Trip share=Trip.from(t.json());File file=File.createTempFile("aa-share-",".zip",c.getCacheDir());try{try(OutputStream out=new FileOutputStream(file)){TripShareArchive.write(c,share,out);}TripShareArchive.Preview preview=TripShareArchive.inspect(c,file);check(preview.members==2&&preview.settlements==1,"share preview actual ledger range",count);ArrayList<Trip> imported=new ArrayList<>();store.save(imported);Trip copy=TripShareArchive.importTrip(c,file,store,imported);check(!copy.members.get(0).id.equals(one.id)&&AaLedger.payments(copy).get(0).amount==30,"actual ZIP remaps ledger and keeps remaining amount",count);check(copy.settlements.get(0).fromId.equals(copy.members.get(1).id)&&copy.expenses.get(0).payerId.equals(copy.members.get(0).id),"ZIP references stay attached",count);JSONObject envelope=new JSONObject(TripStore.encode(Collections.singletonList(copy)));check(envelope.getInt("schema")==3,"new schema protects AA from old writer",count);envelope.put("schema",2);check(TripStore.decode(envelope.toString()).size()==1,"legacy schema remains readable",count);}finally{file.delete();}
   in.runOnMainSync(()->{a.trips.clear();a.trips.add(t);a.active=t;a.save();finance.expense(bill);});in.waitForIdleSync();
   AlertDialog editor=(AlertDialog)field(finance,"draftDialog");EditText draftName=firstEdit((android.view.View)field(finance,"draftForm"));String draftReceipt=new MediaFiles(c).newPath("test",".jpg");File draftFile=MediaFiles.file(c,draftReceipt);draftFile.getParentFile().mkdirs();java.nio.file.Files.write(draftFile.toPath(),new byte[]{1,2,3});in.runOnMainSync(()->{draftName.setText("尚未保存的账单名称");((String[])uncheckedField(finance,"draftPhoto"))[0]=draftReceipt;((ArrayList<String>)uncheckedField(finance,"draftOwned")).add(draftReceipt);});
   in.runOnMainSync(()->{editor.getButton(AlertDialog.BUTTON_NEUTRAL).performClick();});in.waitForIdleSync();AuditHostUiTest.click(in,"取消");in.waitForIdleSync();
   check(editor.isShowing()&&t.expenses.contains(bill)&&draftName.getText().toString().equals("尚未保存的账单名称")&&draftFile.isFile(),"cancel delete keeps expense editor and record",count);
   in.runOnMainSync(()->{a.loadFailed=true;editor.getButton(AlertDialog.BUTTON_NEUTRAL).performClick();});in.waitForIdleSync();AuditHostUiTest.click(in,"确定");in.waitForIdleSync();
   check(editor.isShowing()&&t.expenses.contains(bill),"failed delete rolls back and keeps editor",count);
   in.runOnMainSync(()->{a.loadFailed=false;editor.getButton(AlertDialog.BUTTON_NEUTRAL).performClick();});in.waitForIdleSync();AuditHostUiTest.click(in,"确定");in.waitForIdleSync();
   check(!editor.isShowing()&&!t.expenses.contains(bill),"successful delete dismisses editor",count);
   in.runOnMainSync(a::undoTravel);check(a.active.expenses.stream().anyMatch(e->e.id.equals(bill.id)),"expense deletion is undoable",count);
   in.runOnMainSync(()->finance.expense(a.active.expenses.get(0)));AlertDialog editAgain=(AlertDialog)field(finance,"draftDialog");EditText changedName=firstEdit((android.view.View)field(finance,"draftForm"));in.runOnMainSync(()->{changedName.setText("编辑后餐费");editAgain.getButton(AlertDialog.BUTTON_POSITIVE).performClick();});check(!editAgain.isShowing()&&a.active.expenses.get(0).name.equals("编辑后餐费"),"edit saves and closes only after commit",count);in.runOnMainSync(a::undoTravel);check(a.active.expenses.get(0).name.equals("均摊餐费"),"saved expense edit is undoable",count);
   AaUi team=new AaUi(a);in.runOnMainSync(()->team.members(a.active));in.waitForIdleSync();AlertDialog first=(AlertDialog)field(team,"memberWindow");in.runOnMainSync(()->team.members(a.active));check(!first.isShowing()&&((AlertDialog)field(team,"memberWindow")).isShowing(),"members reopen replaces previous window",count);
   AlertDialog beforeMember=(AlertDialog)field(team,"memberWindow");AuditHostUiTest.click(in,"＋ 添加成员");setFirstEditable(in,"新同行");AuditHostUiTest.click(in,"保存");in.waitForIdleSync();android.os.SystemClock.sleep(100);in.waitForIdleSync();AlertDialog refreshed=(AlertDialog)field(team,"memberWindow");check(!beforeMember.isShowing()&&refreshed.isShowing()&&AuditHostUiTest.find(refreshed.getWindow().getDecorView(),"新同行 · 3")!=null,"new member immediately appears in refreshed list",count);
   in.runOnMainSync(()->((AlertDialog)uncheckedField(team,"memberWindow")).dismiss());in.runOnMainSync(()->team.ledger(a.active));AlertDialog firstLedger=(AlertDialog)field(team,"ledgerWindow");in.runOnMainSync(()->team.ledger(a.active));check(!firstLedger.isShowing()&&((AlertDialog)field(team,"ledgerWindow")).isShowing(),"ledger reopen replaces previous window",count);in.runOnMainSync(()->((AlertDialog)uncheckedField(team,"ledgerWindow")).dismiss());
   return count[0];
  }finally{if(host!=null){MainActivity a=host;in.runOnMainSync(a::finish);in.waitForIdleSync();}store.save(original);store.close();guard.close();}
 }
 private static void check(boolean ok,String label,int[] n){if(!ok)throw new AssertionError(label);n[0]++;}
 private static EditText firstEdit(android.view.View v){if(v instanceof EditText)return (EditText)v;if(v instanceof android.view.ViewGroup){android.view.ViewGroup g=(android.view.ViewGroup)v;for(int i=0;i<g.getChildCount();i++){EditText e=firstEdit(g.getChildAt(i));if(e!=null)return e;}}return null;}
 private static Object field(Object owner,String name)throws Exception{java.lang.reflect.Field f=owner.getClass().getDeclaredField(name);f.setAccessible(true);return f.get(owner);}
 private static Object uncheckedField(Object owner,String name){try{return field(owner,name);}catch(Exception e){throw new AssertionError(e);}}
 private static void setFirstEditable(Instrumentation in,String value){android.view.accessibility.AccessibilityNodeInfo node=null;long deadline=android.os.SystemClock.uptimeMillis()+4000;while(node==null&&android.os.SystemClock.uptimeMillis()<deadline){in.waitForIdleSync();node=editable(in.getUiAutomation().getRootInActiveWindow());if(node==null)android.os.SystemClock.sleep(50);}if(node==null)throw new AssertionError("member name field missing");Bundle b=new Bundle();b.putCharSequence(android.view.accessibility.AccessibilityNodeInfo.ACTION_ARGUMENT_SET_TEXT_CHARSEQUENCE,value);if(!node.performAction(android.view.accessibility.AccessibilityNodeInfo.ACTION_SET_TEXT,b))throw new AssertionError("member name not set");}
 private static android.view.accessibility.AccessibilityNodeInfo editable(android.view.accessibility.AccessibilityNodeInfo n){if(n==null)return null;if(n.isEditable())return n;for(int i=0;i<n.getChildCount();i++){android.view.accessibility.AccessibilityNodeInfo child=editable(n.getChild(i));if(child!=null)return child;}return null;}
}
