package cn.lvxu.travel;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.net.Uri;
import android.os.SystemClock;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.lang.reflect.Field;
import java.util.*;

/** Exercises actual pointer drags and the image import contract on a disposable emulator. */
final class Interaction024Tests {
    private static int count;
    private static void check(boolean value,String label){if(!value)throw new AssertionError(label);count++;}
    static int run(Instrumentation in)throws Exception{
        count=0;Context c=in.getTargetContext();MediaFiles files=new MediaFiles(c);String sourcePath=files.newPath("test",".png"),copyPath=null;MainActivity a=null;
        try{
            Bitmap source=Bitmap.createBitmap(320,160,Bitmap.Config.ARGB_8888);Canvas canvas=new Canvas(source);canvas.drawColor(Color.YELLOW);Paint paint=new Paint();paint.setColor(Color.RED);canvas.drawRect(0,0,80,160,paint);ByteArrayOutputStream bytes=new ByteArrayOutputStream();source.compress(Bitmap.CompressFormat.PNG,100,bytes);source.recycle();java.nio.file.Files.write(files.file(sourcePath).toPath(),bytes.toByteArray());
            copyPath=files.importOriginal(Uri.fromFile(files.file(sourcePath)));check(Arrays.equals(bytes.toByteArray(),java.nio.file.Files.readAllBytes(files.file(copyPath).toPath())),"photo selection preserves original bytes");Bitmap decoded=files.decode(copyPath,400);check(decoded.getWidth()==320&&decoded.getHeight()==160,"photo selection preserves aspect ratio");check(decoded.getPixel(10,80)==Color.RED&&decoded.getPixel(300,80)==Color.YELLOW,"photo selection preserves full frame and colors");decoded.recycle();
            a=(MainActivity)in.startActivitySync(new Intent(c,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP));MainActivity host=a;String imagePath=copyPath;
            Dialog[] viewer={null};in.runOnMainSync(()->viewer[0]=PhotoPreviewUi.show(host,imagePath));in.waitForIdleSync();
            ImageView full=(ImageView)findDescription(viewer[0].getWindow().getDecorView(),"完整照片");check(full!=null&&full.getScaleType()==ImageView.ScaleType.FIT_CENTER&&full.getAlpha()==1f,"full photo preview does not crop or dim");check((viewer[0].getWindow().getAttributes().flags&WindowManager.LayoutParams.FLAG_DIM_BEHIND)==0,"photo preview has no dim layer");in.runOnMainSync(()->findDescription(viewer[0].getWindow().getDecorView(),"关闭图片").performClick());check(!viewer[0].isShowing(),"photo close icon dismisses preview");
            java.util.concurrent.atomic.AtomicReference<String> cropped=new java.util.concurrent.atomic.AtomicReference<>();
            in.runOnMainSync(()->PhotoPreviewUi.crop(host,imagePath,cropped::set));clickLabel(in,"放弃");SystemClock.sleep(200);check(cropped.get()==null,"discard crop does not replace photo");check(Arrays.equals(bytes.toByteArray(),java.nio.file.Files.readAllBytes(files.file(imagePath).toPath())),"discard keeps original bytes");
            in.runOnMainSync(()->PhotoPreviewUi.crop(host,imagePath,cropped::set));clickLabel(in,"保存");for(int attempt=0;attempt<100&&cropped.get()==null;attempt++)SystemClock.sleep(100);check(cropped.get()!=null&&!cropped.get().equals(imagePath),"save crop creates a separate photo");Bitmap square=files.decode(cropped.get(),2000);check(square.getWidth()==square.getHeight(),"explicit crop saves square image");square.recycle();files.file(cropped.get()).delete();check(Arrays.equals(bytes.toByteArray(),java.nio.file.Files.readAllBytes(files.file(imagePath).toPath())),"crop leaves original file intact");
            Trip trip=new Trip();trip.title="排序验证";trip.city="苏州";trip.normalize();for(int i=0;i<3;i++){Trip.Stop stop=new Trip.Stop();stop.name="地点 "+(char)('A'+i);stop.time=new String[]{"09:00","10:00","11:00"}[i];stop.duration=30;trip.stops.add(stop);}String firstId=trip.stops.get(0).id,secondId=trip.stops.get(1).id;
            in.runOnMainSync(()->{host.trips.clear();host.trips.add(trip);host.active=trip;host.page=1;host.day=0;host.mapMode=false;host.changed();});in.waitForIdleSync();
            StopReorderLayout list=(StopReorderLayout)findClass(host.body,StopReorderLayout.class);ScrollView scroll=(ScrollView)host.body.getParent();in.runOnMainSync(()->scroll.scrollTo(0,list.getTop()));in.waitForIdleSync();
            SystemClock.sleep(250);Rect first=bounds(list.getChildAt(0)),second=bounds(list.getChildAt(1));gesture(in,first.left+host.dp(40),first.top+host.dp(60),second.left+host.dp(40),second.centerY()+host.dp(16),true);SystemClock.sleep(400);in.waitForIdleSync();
            check(trip.onDay(0).get(0).id.equals(secondId)&&trip.onDay(0).get(1).id.equals(firstId),"long press drag reorders places first="+first+" second="+second+" actual="+trip.onDay(0).get(0).name+","+trip.onDay(0).get(1).name);check(trip.stops.size()==3&&trip.stops.get(0).time.equals("09:00"),"drag preserves places and times");check(host.store.read().get(0).onDay(0).get(0).id.equals(secondId),"drag order persisted");
            in.runOnMainSync(()->{host.page=0;host.showArchived=false;host.render();});in.waitForIdleSync();check(findText(host.body,"已归档旅行")==null,"archive entry removed from normal home");
            SwipeActionsLayout swipe=(SwipeActionsLayout)findClass(host.body,SwipeActionsLayout.class);ScrollView homeScroll=(ScrollView)host.body.getParent();in.runOnMainSync(()->homeScroll.scrollTo(0,host.body.getHeight()));in.waitForIdleSync();Rect card=bounds(swipe);gesture(in,card.centerX(),card.top+host.dp(55),card.centerX()-host.dp(24),card.top+host.dp(55),false);SystemClock.sleep(300);check(swipe.isOpen(),"short swipe opens actions");check(Math.abs(swipe.getChildAt(1).getTranslationX())<=host.dp(177),"action reveal stays compact");in.runOnMainSync(host::onBackPressed);SystemClock.sleep(300);check(!swipe.isOpen()&&!host.isFinishing(),"back closes actions before exiting");
            in.runOnMainSync(()->host.settings.open());SystemClock.sleep(360);Field current=SettingsUi.class.getDeclaredField("current");current.setAccessible(true);Dialog config=(Dialog)current.get(host.settings);check(config!=null&&config.getWindow().getAttributes().width==WindowManager.LayoutParams.MATCH_PARENT,"configuration fills screen width");TextView title=(TextView)findText(config.getWindow().getDecorView(),"配置");check(title!=null&&(title.getGravity()&Gravity.CENTER_HORIZONTAL)!=0,"configuration title centered");View avatar=findDescription(config.getWindow().getDecorView(),"更换头像");check(avatar!=null&&avatar.getClipToOutline(),"configuration avatar clips to round outline");View archive=findDescription(config.getWindow().getDecorView(),"已归档旅行  ›"),about=findText(config.getWindow().getDecorView(),"关于");check(archive!=null&&about!=null&&bounds(archive).top<bounds(about).top,"archive entry precedes about");in.runOnMainSync(config::onBackPressed);check(config.isShowing(),"configuration back animates before dismiss");SystemClock.sleep(360);check(!config.isShowing(),"configuration exit completes");
            return count;
        }finally{if(a!=null){MainActivity host=a;in.runOnMainSync(host::finish);}files.file(sourcePath).delete();if(copyPath!=null)files.file(copyPath).delete();}
    }
    private static void clickLabel(Instrumentation in,String label){for(int i=0;i<100;i++){android.view.accessibility.AccessibilityNodeInfo root=in.getUiAutomation().getRootInActiveWindow();if(root!=null){for(android.view.accessibility.AccessibilityNodeInfo node:root.findAccessibilityNodeInfosByText(label)){if(label.contentEquals(node.getText()==null?"":node.getText())&&node.isClickable()){SystemClock.sleep(250);node.performAction(android.view.accessibility.AccessibilityNodeInfo.ACTION_CLICK);return;}}}SystemClock.sleep(100);}throw new AssertionError("Missing photo action "+label);}
    private static Rect bounds(View v){int[] p=new int[2];v.getLocationOnScreen(p);return new Rect(p[0],p[1],p[0]+v.getWidth(),p[1]+v.getHeight());}
    private static View findDescription(View root,String text){if(text.contentEquals(root.getContentDescription()==null?"":root.getContentDescription()))return root;if(root instanceof ViewGroup){ViewGroup group=(ViewGroup)root;for(int i=0;i<group.getChildCount();i++){View found=findDescription(group.getChildAt(i),text);if(found!=null)return found;}}return null;}
    private static View findText(View root,String text){if(root instanceof TextView&&text.contentEquals(((TextView)root).getText()))return root;if(root instanceof ViewGroup){ViewGroup group=(ViewGroup)root;for(int i=0;i<group.getChildCount();i++){View found=findText(group.getChildAt(i),text);if(found!=null)return found;}}return null;}
    private static View findClass(View root,Class<?> type){if(type.isInstance(root))return root;if(root instanceof ViewGroup){ViewGroup group=(ViewGroup)root;for(int i=0;i<group.getChildCount();i++){View found=findClass(group.getChildAt(i),type);if(found!=null)return found;}}return null;}
    private static void gesture(Instrumentation in,float x,float y,float endX,float endY,boolean hold){long down=SystemClock.uptimeMillis();send(in,down,MotionEvent.ACTION_DOWN,x,y);SystemClock.sleep(hold?ViewConfiguration.getLongPressTimeout()+180:40);for(int i=1;i<=16;i++){send(in,down,MotionEvent.ACTION_MOVE,x+(endX-x)*i/16,y+(endY-y)*i/16);SystemClock.sleep(18);}send(in,down,MotionEvent.ACTION_UP,endX,endY);}
    private static void send(Instrumentation in,long down,int action,float x,float y){MotionEvent event=MotionEvent.obtain(down,SystemClock.uptimeMillis(),action,x,y,0);event.setSource(InputDevice.SOURCE_TOUCHSCREEN);if(!in.getUiAutomation().injectInputEvent(event,true))throw new AssertionError("touch injection failed");event.recycle();}
}
