package cn.lvxu.travel;
import android.content.*;
import java.util.*;
import org.json.*;
final class NearbyDiscoveryCacheTest {
 static int run(Context c)throws Exception{SharedPreferences prefs=c.getSharedPreferences("nearby-discovery-cache-v1",0);String previous=prefs.getString("data",null);int n=0;try{prefs.edit().clear().commit();NearbyDiscoveryCache cache=new NearbyDiscoveryCache(c);NearbyPlace p=new NearbyPlace("cache-test","测试地点","","兰州市","人文",36.06,103.8,4f);cache.putPlaces("兰州市","人文",Arrays.asList(p));n+=check(new NearbyDiscoveryCache(c).getPlaces("兰州市","人文").size()==1,"POIs persist");n+=check(cache.getPlaces("兰州市","美食").isEmpty(),"categories isolated");long now=System.currentTimeMillis();cache.putHeat(p,3,now);cache.putHeat(p,0,now+1);cache.applyHeat(p);n+=check(p.heat==3&&p.heatAt==now,"unknown cannot replace valid heat");cache.putHeat(p,5,now-1);cache.applyHeat(p);n+=check(p.heat==3,"old sample cannot replace newer");NearbyPlace moved=new NearbyPlace("cache-test","测试地点","","兰州市","人文",36.07,103.8,4f);cache.applyHeat(moved);n+=check(moved.heat==0,"heat bound to coordinate");cache.clearHeat("兰州市");cache.applyHeat(p);n+=check(p.heat==0,"manual region heat clearing");cache.putHeat(p,5,now-NearbyDiscoveryCache.TTL_MS-1);cache.applyHeat(p);n+=check(p.heat==5&&p.staleHeat(),"stale heat retained");cache.putHeat(p,0,now);cache.applyHeat(p);n+=check(p.heat==5,"unknown cannot wipe stale heat");cache.prune();cache.applyHeat(p);n+=check(p.heat==5,"thirty-minute prune preserves old reference");
  n+=check(cache.refreshDue("兰州市"),"never completed refresh is due");cache.markCompleteRefresh("兰州市",now);n+=check(!cache.refreshDue("兰州市")&&cache.lastCompleteRefresh("兰州市")==now,"only explicit completion changes due time");n+=check(cache.shouldRefresh("兰州市",now+NearbyDiscoveryCache.TTL_MS+1),"completed refresh due after thirty minutes");
  NearbyPlace batch=new NearbyPlace("batch","测试地点二","","兰州市","人文",36.061,103.8,4f);batch.heat=1;batch.heatAt=now;cache.putHeatBatch("兰州市",Arrays.asList(batch));cache.applyHeat(batch);n+=check(batch.heat==1,"batch persists reliable heat");
  JSONObject data=new JSONObject(prefs.getString("data","{}"));data.getJSONObject("pois").getJSONObject("兰州市|人文").put("at",now-NearbyDiscoveryCache.TTL_MS-1);prefs.edit().putString("data",data.toString()).commit();n+=check(!cache.placesFresh("兰州市","人文")&&cache.getPlaces("兰州市","人文").size()==1,"stale POIs available while refresh due");
  data=new JSONObject(prefs.getString("data","{}"));data.getJSONObject("heat").getJSONObject(p.id).put("at",now-NearbyDiscoveryCache.RETENTION_MS-1);data.getJSONObject("pois").getJSONObject("兰州市|人文").put("at",now-NearbyDiscoveryCache.RETENTION_MS-1);prefs.edit().putString("data",data.toString()).commit();cache.prune();cache.applyHeat(p);n+=check(p.heat==0&&cache.getPlaces("兰州市","人文").isEmpty(),"seven-day retention purges old entries");
  cache.putHeat(batch,3,now+60_000);cache.applyHeat(batch);n+=check(batch.heat==1,"future sample cannot overwrite known reference");n+=check(cache.regions().contains("兰州市"),"region metadata available without fix");cache.clearPlaces("兰州市");n+=check(cache.getPlaces("兰州市","人文").isEmpty(),"manual region POI clearing");return n;}finally{SharedPreferences.Editor e=prefs.edit().clear();if(previous!=null)e.putString("data",previous);e.commit();}}
 private static int check(boolean b,String m){if(!b)throw new AssertionError(m);return 1;}
}
