package cn.lvxu.travel;
import android.app.*;import android.content.*;import android.view.*;import android.widget.*;import android.os.SystemClock;import org.json.*;import java.util.*;
final class StageOneThemeTests {
 static int run(Instrumentation in)throws Exception{Context c=in.getTargetContext();AppPrefs prefs=new AppPrefs(c);JSONObject original=prefs.exportJson();MainActivity a=null;int n=0;try{prefs.setTutorialDone(true);prefs.setLastUpdateDay(java.time.LocalDate.now().toString());a=(MainActivity)in.startActivitySync(new Intent(c,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP));final MainActivity host=a;
 for(String mode:new String[]{"light","dark"})for(String id:ThemeColors.IDS){in.runOnMainSync(()->{prefs.setTheme(mode);prefs.setColorPreset(id);host.page=0;host.render();});in.waitForIdleSync();check(MainActivity.DARK==mode.equals("dark"),"mode selection");n++;check(ThemeColors.contrast(MainActivity.PRIMARY_TEXT,MainActivity.GREEN)>=4.5,"primary text contrast");n++;capture(in,"stage1-"+id+"-"+mode+".png");}
 JSONObject custom=new JSONObject().put("light",new JSONObject().put("primary","#FFEEDD").put("bg","#FFFFFF").put("surface","#101010").put("pale","#F3E7FF"));prefs.setCustomColors(custom);prefs.setTheme("light");in.runOnMainSync(host::render);in.waitForIdleSync();check(new AppPrefs(c).customColorsEnabled()&&new AppPrefs(c).customColors().getJSONObject("light").getString("primary").equals("#FFEEDD"),"custom persists");n++;check(MainActivity.GREEN==ThemeColors.parseHex("#FFEEDD"),"custom primary used");n++;final Spinner[] spinner={null};final TextView[] rebound={null};in.runOnMainSync(()->{LinearLayout form=host.col();spinner[0]=host.select(form,"测试选择",new String[]{"旅行","打卡"},"旅行");rebound[0]=(TextView)spinner[0].getAdapter().getView(1,null,form);});check(ThemeColors.contrast(rebound[0].getCurrentTextColor(),MainActivity.SURFACE)>=4.5,"rebound spinner text remains readable");n++;JSONObject backup=prefs.exportJson();prefs.resetColors();prefs.importJson(backup);check(prefs.customColorsEnabled(),"custom backup roundtrip");n++;boolean bad=false;try{prefs.setCustomColors(new JSONObject().put("light",new JSONObject().put("primary","#12")));}catch(IllegalArgumentException e){bad=true;}check(bad&&prefs.customColors().toString().equals(custom.toString()),"invalid input preserves saved colors");n++;
 in.runOnMainSync(()->{prefs.resetColors();prefs.setTheme("light");host.render();new ThemeSettingsUi(host).show(host::render);});in.waitForIdleSync();SystemClock.sleep(300);capture(in,"stage1-colors.png");in.getUiAutomation().performGlobalAction(1);SystemClock.sleep(200);
 final AlertDialog[] d={null};in.runOnMainSync(()->d[0]=new RoundedDialogs.Builder(host).setTitle("圆角确认").setMessage("文字、按钮和背景保持清晰").setPositiveButton("确定",null).show());in.waitForIdleSync();SystemClock.sleep(250);check(d[0].getWindow().getDecorView().getBackground()!=null,"dialog background present");n++;capture(in,"stage1-dialog.png");in.runOnMainSync(d[0]::dismiss);
 Trip trip=Trip.demo();in.runOnMainSync(()->{host.trips.clear();host.trips.add(trip);host.active=trip;host.page=0;host.render();});in.waitForIdleSync();View swipe=find(host.body,SwipeActionsLayout.class);in.runOnMainSync(()->{ScrollView scroll=(ScrollView)host.body.getParent();scroll.scrollTo(0,host.body.getHeight());});in.waitForIdleSync();java.lang.reflect.Method settle=SwipeActionsLayout.class.getDeclaredMethod("settle",boolean.class);settle.setAccessible(true);in.runOnMainSync(()->{try{settle.invoke(swipe,true);}catch(Exception e){throw new RuntimeException(e);}});SystemClock.sleep(350);ViewGroup actions=(ViewGroup)((ViewGroup)swipe).getChildAt(0);for(int row=0;row<2;row++){ViewGroup group=(ViewGroup)actions.getChildAt(row);for(int col=0;col<2;col++){ViewGroup tile=(ViewGroup)group.getChildAt(col);TextView label=(TextView)tile.getChildAt(tile.getChildCount()-1);check((label.getGravity()&Gravity.HORIZONTAL_GRAVITY_MASK)==Gravity.CENTER_HORIZONTAL,"swipe label centered");n++;}}capture(in,"stage1-swipe.png");return n;
 }finally{prefs.importJson(original);if(a!=null){MainActivity host=a;in.runOnMainSync(host::finish);}}}
 static void capture(Instrumentation in,String name)throws Exception{SystemClock.sleep(120);android.graphics.Bitmap b=in.getUiAutomation().takeScreenshot();if(b!=null){try(java.io.FileOutputStream out=new java.io.FileOutputStream(new java.io.File(in.getTargetContext().getExternalFilesDir(null),name))){b.compress(android.graphics.Bitmap.CompressFormat.PNG,100,out);}b.recycle();}}
 static View find(View v,Class<?> type){if(type.isInstance(v))return v;if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++){View x=find(g.getChildAt(i),type);if(x!=null)return x;}}return null;}
 static void check(boolean value,String label){if(!value)throw new AssertionError(label);}
}
