package cn.lvxu.travel;
import android.app.*;import android.content.*;import android.view.*;import android.widget.*;import java.util.*;import java.lang.reflect.*;
final class TravelSafetyUiTest {
 static int run(Instrumentation in)throws Exception{Context context=in.getTargetContext();TripStore originalStore=new TripStore(context);ArrayList<Trip> original=originalStore.read();TestStartupGuard guard=new TestStartupGuard(context);MainActivity a=(MainActivity)in.startActivitySync(new Intent(context,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));in.waitForIdleSync();int count=0;
  try{Trip trip=Trip.demo();trip.title="兰州三日出游验收";trip.city="兰州市";trip.days=3;trip.stops.clear();Trip.Stop museum=new Trip.Stop();museum.name="甘肃省博物馆";museum.time="09:00";museum.timeLocked=true;Trip.Stop food=new Trip.Stop();food.name="兰州牛肉面";food.time="12:00";trip.stops.add(museum);trip.stops.add(food);
   in.runOnMainSync(()->{a.trips.clear();a.trips.add(trip);a.active=trip;a.page=1;a.day=0;a.save();a.render();a.stopEditor(food);});in.waitForIdleSync();Field dialogField=MainActivity.class.getDeclaredField("stopDraftDialog");dialogField.setAccessible(true);AlertDialog edit=(AlertDialog)dialogField.get(a);ArrayList<EditText> fields=new ArrayList<>();collect(edit.getWindow().getDecorView(),fields);EditText name=fields.get(0);
   in.runOnMainSync(()->{name.setText("未保存的午餐备注");edit.getButton(-3).performClick();});in.waitForIdleSync();check(edit.isShowing(),"delete confirmation closed stop draft");count++;in.getUiAutomation().performGlobalAction(android.accessibilityservice.AccessibilityService.GLOBAL_ACTION_BACK);in.waitForIdleSync();check(edit.isShowing()&&name.getText().toString().equals("未保存的午餐备注"),"cancel delete lost edits");count++;in.runOnMainSync(edit::dismiss);
   in.runOnMainSync(()->{check(a.deleteStop(trip,food),"stop deletion save failed");});check(trip.stops.size()==1&&a.travelUndo!=null,"stop deletion did not offer undo");count++;in.runOnMainSync(a::undoTravel);check(a.active.stops.size()==2&&a.active.stops.get(1).id.equals(food.id),"undo lost stop identity");count++;
   Method preview=TravelAdjustmentUi.class.getDeclaredMethod("preview",MainActivity.class,Trip.class,int.class,int.class);preview.setAccessible(true);in.runOnMainSync(()->{try{preview.invoke(null,a,a.active,0,30);}catch(Exception e){throw new AssertionError(e);}});in.waitForIdleSync();View apply=find(in.getUiAutomation(),a,"应用调整");check(apply!=null,"adjustment preview missing apply action");count++;in.runOnMainSync(apply::performClick);in.waitForIdleSync();check(a.active.stops.get(0).time.equals("09:00")&&a.active.stops.get(1).time.equals("12:30"),"locked appointment shifted or lunch did not shift");count++;in.runOnMainSync(a::undoTravel);check(a.active.stops.get(1).time.equals("12:00"),"batch adjustment not undoable");count++;
   Trip beforeFailure=a.active;a.store.getWritableDatabase().execSQL("CREATE TEMP TRIGGER travel_write_fail BEFORE INSERT ON snapshot BEGIN SELECT RAISE(ABORT,'fixture'); END");try{in.runOnMainSync(()->check(!a.deleteStop(beforeFailure,beforeFailure.stops.get(1)),"failed deletion claimed success"));check(beforeFailure.stops.size()==2&&a.travelUndo==null,"failed deletion lost original or recorded undo");count++;}finally{a.store.getWritableDatabase().execSQL("DROP TRIGGER travel_write_fail");}
   in.runOnMainSync(()->{a.page=1;a.render();});in.waitForIdleSync();android.os.SystemClock.sleep(3500);try(java.io.FileOutputStream screenshot=new java.io.FileOutputStream(new java.io.File(context.getExternalFilesDir(null),"travel-experience-itinerary.png"))){in.getUiAutomation().takeScreenshot().compress(android.graphics.Bitmap.CompressFormat.PNG,100,screenshot);}
   return count;
  }finally{in.runOnMainSync(a::finish);in.waitForIdleSync();originalStore.save(original);originalStore.close();guard.close();}
 }
 private static View find(android.app.UiAutomation ignored,MainActivity a,String label){View root=a.getWindow().getDecorView();View found=find(root,label);if(found!=null)return found; // Dialog windows are separate from the Activity decor.
  try{Class<?> global=Class.forName("android.view.WindowManagerGlobal");Method get=global.getDeclaredMethod("getInstance");Object instance=get.invoke(null);Field views=global.getDeclaredField("mViews");views.setAccessible(true);for(Object value:(java.util.List<?>)views.get(instance)){found=find((View)value,label);if(found!=null)return found;}}catch(Exception e){throw new AssertionError(e);}return null;}
 private static View find(View root,String label){if(root instanceof TextView&&label.contentEquals(((TextView)root).getText()))return root;if(root instanceof ViewGroup){ViewGroup g=(ViewGroup)root;for(int i=0;i<g.getChildCount();i++){View v=find(g.getChildAt(i),label);if(v!=null)return v;}}return null;}
 private static void collect(View root,ArrayList<EditText> fields){if(root instanceof EditText)fields.add((EditText)root);if(root instanceof ViewGroup){ViewGroup g=(ViewGroup)root;for(int i=0;i<g.getChildCount();i++)collect(g.getChildAt(i),fields);}}
 private static void check(boolean value,String label){if(!value)throw new AssertionError(label);}
}
